(function() {

  SU.addProps(ST, {
    cargoName: function(seed, level, type) {
			var result = "";
			if (type == SF.CARGO_ORE) {
				result = ST.randText(ST.pickupAdj, seed+1)+" "+ST.randText(ST.mineralAdj, seed+2)+" "+ST.randText(ST.mineral, seed+3);
			} else if (type == SF.CARGO_GOODS) {
				result = ST.randText(ST.pickupAdj, seed+4)+" "+ST.randText(ST.shinyAdj, seed+5)+" "+ST.randText(ST.shiny, seed+6);
			} else {  // Contraband.
				result = ST.randText(ST.pickupAdj, seed+7)+" "+ST.randText(ST.shinyAdj, seed+8)+" "+ST.randText(ST.contraband, seed+9);
			}
			return result; //result.charAt(0).toUpperCase() + result.toLowerCase().substring(1, result.length); 
    },
		/*
    pickupAdj: [// 0 to 10, originally, so removed for now.
        ["Nonexistent", "Negligible", "Imperceptible", "Terrible"],
        ["Broken", "Toy", "Poor", "Trivial", "Petty", "Minute"],
        ["Degenerate", "Soft", "Meager", "Shabby", "Subpar", "Platry"],
        ["Imitation", "Minor", "Shoddy", "Weak", "Imperfect", "Inferior"],
        ["Flawed", "Small", "Mediocre", "Common", "Dull"],
        ["Useful", "Adequate", "Plain", "Sufficient", "Unbroken", "Fair", "Tolerable"],
        ["Valued", "Healthy", "Major", "Sound", "Unmarred"],
        ["Quality", "Hefty", "Significant", "Excellent", "Superior"],
        ["Refined", "Great", "Potent", "Strong", "Exceptional"],
        ["Flawless", "Heroic", "Grand", "Noble", "Extraordinary"],
        ["Perfect", "Impeccable", "Unmatched", "Stellar", "Incredible"]
    ],
		*/		
		pickupAdj: [
        "Nonexistent", "Negligible", "Imperceptible", "Terrible",
        "Broken", "Toy", "Poor", "Trivial", "Petty", "Minute",
        "Degenerate", "Soft", "Meager", "Shabby", "Subpar", "Platry",
        "Imitation", "Minor", "Shoddy", "Weak", "Imperfect", "Inferior",
        "Flawed", "Small", "Mediocre", "Common", "Dull",
        "Useful", "Adequate", "Plain", "Sufficient", "Unbroken", "Fair", "Tolerable",
        "Valued", "Healthy", "Major", "Sound", "Unmarred",
        "Quality", "Hefty", "Significant", "Excellent", "Superior",
        "Refined", "Great", "Potent", "Strong", "Exceptional",
        "Flawless", "Heroic", "Grand", "Noble", "Extraordinary",
        "Perfect", "Impeccable", "Unmatched", "Stellar", "Incredible",
		],
		mineralAdj: [
			"Irradiated",
			"Unusual",
			"Rare",
			"Bizarre",
			"Glowing",
			"Composite",
			"Circular",
			"Shining",
			"Fire",
			"Heated",
			"Preserved",
			"Aged",
			"Antique",
			"Wild",
			"Mystic",
			"Orange",
			"New",
			"Strange",
			"Odd",
			"Textured",
			"Resistant",
			"Reinforced",
			"Hexagonal",
			"Lit",
			"Eerie",
			"Reversed",
			"Mixed",
			"Pure",
			"Ancient",
			"Wispy",
			"Buoyant",
			"Explosive",
			"Energetic",
			"Heavy",
			"Foreign",
			"Unknown",
			"Extreme",
			"Shimmering",
			"Partly dissolved",
		],
    mineral: [
        // Fake/funny minerals
        "Unununium",
        "Moronic Acid",
        "Mooninite",
        // Standard
        "Gold",
        "Silver",
        "Uranium",
        "Lead",
        "Galena",
        "Mercury",
        "Allophane",
        "Hisingerite",
        "Chrysotile",
        "Wadsleyite",
        "Bamfordite",
        "Baryte",
        "Becquerelite",
        "Breithauptite",
        "Brucite",
        "Evenkite",
        "Ekanite",
        "Imogolite",
        "Iridium",
        "Ixiolite",
        "Orthoclase",
        "Osmium",
        "Overite",
        "Tangeite",
        "Tarbuttite",
        "Tellurite",
        "Thenardite",
        "Thorite",
        "Titanite",
        "Trona",
        "Tyrolite",
        "Agrellite",
        "Aksaite",
        "Albite",
        "Alstonite",
        "Amesite",
        "Anglesite",
        "Apachite",
        "Atacamite",
        "Avogadrite",
        "Azurite",
        "Cadmium",
        "Calciborite",
        "Caledonite",
        "Calomel",
        "Carnotite",
        "Cavansite",
        "Cesanite",
        "Charoite",
        "Chloritoid",
        "Chromite",
        "Crocoite",
        "Curite",
        "Diaboleite",
        "Diamond",
        "Dolomite!",
        "Dravite",
        "Dypingite",
        "Fabianite",
        "Ferberite",
        "Ferrogedrite",
        "Fettelite",
        "Fluorite",
        "Fornacite",
        "Freibergite",
        "Galaxite",
        "Gananite",
        "Gedrite",
        "Geocronite",
        "Gibbsite",
        "Gypsum",
        "Halite",
        "Hauerite",
        "Hectorite",
        "Hercynite",
        "Hopeite",
        "Hydrohalite",
        "Janggunite",
        "Jixianite",
        "Jordanite",
        "Kainite",
        "Kangite",
        "Kanoite",
        "Kassite",
        "Keilite",
        "Kieftite",
        "Kinoite",
        "Kostovite",
        "Krutovite",
        "Lanarkite",
        "Lanthanite",
        "Laurite",
        "Lawsonite",
        "Leightonite",
        "Leucite",
        "Liebigite",
        "Liroconite",
        "Lulzacite",
        "Lyonsite",
        "Magadiite",
        "Magnesite",
        "Magnetite",
        "Manganosite",
        "Marcasite",
        "Massicot",
        "Mayenite",
        "Mazzite",
        "Mereheadite",
        "Mesolite",
        "Microlite",
        "Mimetite",
        "Mirabilite",
        "Monimolite",
        "Moolooite",
        "Mordenite",
        "Mosesite",
        "Mundite",
        "Nambulite",
        "Natron",
        "Nelenite",
        "Nickel",
        "Nierite",
        "Niter",
        "Nsutite",
        "Pabstite",
        "Palladium",
        "Paragonite",
        "Paratellurite",
        "Pearceite",
        "Pectolite",
        "Periclase",
        "Petzite",
        "Pigeonite",
        "Platinum",
        "Pollucite",
        "Portlandite",
        "Prehnite",
        "Proustite",
        "Pyrite",
        "Quintinite",
        "Rameauite",
        "Realgar",
        "Renierite",
        "Rhodizite",
        "Rollandite",
        "Rossmanite",
        "Ruizite",
        "Rutile",
        "Ruthenium",
        "Sabieite",
        "Sanidine",
        "Saponite",
        "Scheelite",
        "Schorl",
        "Scorodite",
        "Semseyite",
        "Shortite",
        "Sodalite",
        "Spinel",
        "Staurolite",
        "Stibarsen",
        "Sudoite",
        "Susannite",
        "Sweetite",
        "Syngenite",
        "Umbite",
        "Ulrichite",
        "Uricite",
        "Vaesite",
        "Vaterite",
        "Villiaumite",
        "Volborthite",
        "Vulcanite",
        "Wardite",
        "Wavellite",
        "Wenkite",
        "Willemite",
        "Wulfenite",
        "Xifengite",
        "Xonotlite",
        "Yttrialite",
        "Zaherite",
        "Zeunerite",
        "Zincochromite",
        "Zinkenite",
        "Zoisite",
        "Zunyite",
        "Zussmanite"
    ],
		shinyAdj: [
			"Golden",
			"Rubber",
			"Hardy",
			"Exquisite",
			"Constructed",
			"Fusion",
			"Energy",
			"Fire",
			"Billiard",
			"Medicinal",
			"Hypnotic",
			"Aquatic",
			"Poisonous",
			"Growth",
			"Rare",
			"Distilled",
			"Nutritional",
			"Heavy",
			"Auto",
			"Assorted",
			"Children's",
			"Network",
			"Terraforming",
		],
		// Some of these in homage to Starflight.
    shiny: [
      "Mold",
      "Technologies",
      "Toys",
      "Trumpets",
      "Reactors",
      "Water",
      "Crystals",
      "Vines",
      "Flamewater",
      "Gemstones",
      "Insects",
      "Elixir",
      "Fauna",
      "Lifeforms",
      "Instruments",
      "Foam",
      "Spheres",
      "Fluid",
      "Crystals",
      "Lasers",
      "Pearls",
      "Baubble",
      "Carpeting",
      "Amoebas",
      "Ducky",
      "Amoebasy",
      "Cape",
      "Motorcycle",
      "Doubloon",
      "Pepperoni Pizza",
      "Jet pack",
      "Chocolate cow",
      "Candy cane",
      "Drumset",
      "Treehouse",
      "Robot",
      "Baubble",
      "Glass",
      "Shiny",
      "Sapphire",
      "Tinsel",
      "Polished Metal",
      "Mirror Shard",
      "Ring",
      "Aluminum Foil",
      "Pearl",
      "Shiny",
      "Coin",
      "Garden Globe",
      "Glass Bead",
      "Glass Bottle",
      "Aluminum Can",
      "Tin Can",
      "Prism",
      "Rock Candy",
      "Metal Bolt",
      "Silver Fork",
      "Bling",
      "Brass Bell",
      "Tinfoil",
      "Fiber Cable",
      "Candy Wrapper",
      "Blank CD",
      "Blank DVD",
      "Coffee Pot",
      "Glass Bubble",
      "Paperweight",
      "Police Badge",
      "Fish Hook",
      "Keys",
      "Deadbolt",
      "Copper Pipe",
      "Wire",
      "Wrench",
      "Scissors",
      "Paperclip",
      "Bar Magnet",
      "Kettle",
      "Bucket",
      "Nail",
      "Watch",
      "Pocketwatch",
      "Washer",
      "Bolt",
      "Gear",
      "Sprocket",
      "Monopoly Piece",
      "Wine Glass",
      "Shot Glass",
      "Amber",
      "Amethyst",
      "Aquamarine",
      "Apatite",
      "Citrine",
      "Cubic Zirconia",
      "Garnet",
      "Iolite",
      "Jet",
      "Larimar",
      "Marcasite",
      "Moissanite",
      "Topaz",
      "Peridot",
      "Quartz",
      "Ruby",
      "Sapphire",
      "Spinel",
      "Tanzanite",
      "Turquiose"
    ],
    contraband: [
      "Dope",
      "Grass",
      "Skunk",
      "Cheeb",
      "Trees",
      "Greens",
      "Schwag",
      "Herb",
      "Red",
      "Ace",
      "Black",
      "White",
      "Ash",
      "Bag",
      "Bash",
      "Blonde",
      "Bomber",
      "Chase",
      "Cube",
      "Dew",
      "Dope",
      "Dust",
      "Fry",
      "Hair",
      "Hay",
      "Key",
      "Lace",
      "Leaf",
      "Primo",
      "Gorilla",
      "Pod",
      "Seeds",
      "Sugar",
    ],		
  });
})();


