(function() {

	SU.addProps(ST, {
		barPin: function(seed, faction) {
			if (faction === SF.FACTION_NORMAL) {
				return ST.randText(ST.barPinNormal1, seed + 50);
			} else {
				return ST.randText(ST.barPinPirate1, seed + 50);
			}
		},
		barPinNormal1: [
			"42",
			"Who killed the world?",  // Max Max.
			"Who broke the world?",  // Max Max.
			"The World is on Fire",  // It always has been.
			"Space Emerges",  // Emergent game.
			"07734",  // Hello on calculator.
			"All substance and no show",
			"Particularly beautiful day",  // Sunshine movie quote.
			"Only dream I ever have",  // Sunshine Movie quote.
			"Do me a solid",
			"Ps. 139",
			"Welcome",
			"Space Camp Grad",
			"Too Many Secrets",  // Snearkers movie.
			"Live Long and Prosper",  // Star Trek.
			"Nanu Nanu",  // Mork and Mindy.
			"Armchair Physicist",
			"Take You to My Leader",  // Cliche.
			"All In the Journey",
			"Talk to Me",
			"Can't Stop the Rain",
			"Too Legit to Quit",  // MC Hammer.
			"All Righty Then",  // Jim Carey.
			"Han Shot First",  // Star Wars controversy.
			"Slightly Ahead of Time",
			"Best Chain Beer",
			"Potential is Limitless!",
			"Life is but a Dream",  // Row, row, row your boat.
			"Dream Big",
			"Stars in Eyes",  // Juke box hero.
			"The Struggle is Real",
			"Go For It",
			"Brodown",
			"You're the Navigator",  // Flight of the navigator.
			"Dry Sponge = Happy Sponge",  // Aqua Teen?
			"War is Shame",
			"Illusion of Reality",
			"Gone Legit",
			"Pack Light",
			"Carry In Carry Out",
			"John Doe",
			"How's Your Mama?",
			"Closing Time",
			"Drunks Sent Home",
			"Carpe Vinum",
			"Unum Sumus",
			"Don't Quit Your Day Job",
			"Gamekeeper",
			"Game Day",
			"Game Plan?",
			"Don't Be Evil",
			"Try To Do Good",
			"Seriously Op",
			"Therapist",
			"Al Coholic",
			"A Fight is Brewing",
			"Expanding Universe",
			"Exclamation!",
			"Awkward!",
			"Thanks For All The Fish",  // Douglas Adams, and the babelfish in player's ear.
			"It Just Got Weird",
			"Yeah, Baby!",
			"Hotten Than You",
			"Search for More Money",  // Spaceballs.
			"Explicative Deleted",
			"Super Meatball Boy",
			"Call Me Maybe?",
			"Never Trust Atoms",
			"Works for Tips",
			"Filtered by Reverse Osmosis",
			"Rood Rallec",  // Cellar Door, famous phrase.
			"Friend or Foe?",
			"Dungeon Master",
			"Everything is Awesome",
			"Don't Listen to Me",
			"Flash Mob of 1",
			"Reality is in Fact Virtual",
			"Retirony",
			"You the Man!",
			"Human? Who Are We To Answer?",
			"Out Of This World",
			"Don't Drink And Fly",
			"Taser",
			"In a World...",
			"One Gold Piece",
			"It's Been Real",
			"Eekum Bokum",
			"They Came From Behind",  // Starcraft?
			"This Planet Turns Slowly",  // Fireflies song.
			"My Smiley Face",
			"Ensemble Cast",
			"Ridiculously Photogenic",
			"True Story",
			"True Story Bro",
			"Cool Story",
			"Cool Story Bro",
			"Rule 63",
			"Are You a Wizard?",
			"Fried Mudkips?",
			"Beep Boop",
			"Smurf Bar",
			"Oxygen Bar",
			"Wine Bar",
			"Milk Bar",
			"Parallel Bar",
			"Salad Bar",
			"Scroll Bar",
			"Space Bar",
			"Cash Bar",
			"Candy Bar",
			"Where Do I Find Wood?",  // DOTA.
			"This Is It",
			"4.. 3.. 2.. 1..",
			"All Y'all Come Back Now",
			"I'd Rather Be Fishing",
			"Every Day I'm Waffling",  // LMFAO shuffling.
			"Cold Planets are Sublime",
			"Disco Night",
			"Millionaire",
			"I'm Vegan",
			"Wish Upon a Star",
			"Poor Shubs and Zuuls",  // Ghostbusters.
			"Tell Me About Your Mother",  // Freud in Bill & Ted's.
			"Cairny",  // Diablo-ish.
			"Cellar Door",  // Famous perfect phrase.
			"Last Year Called",
			"Stay on Target",  // Star Wars.
			"For Great Science",
			"Close Encounter",
			"LMAO",
			"Mooninite",  // ATHF.
			"Snacks in Moderation",  // Civ IV.
			"I'm a Fungi",  // Old joke.
			"Exploration of Space",
			"Follow Your Dreams",
			"Worth It",
			"Human? Or Dancer?",  // Song lyrics.
			"Heads in the Game",
			"Numbers Game",
			"Patience",  // WoW (undead).
			"Disclipline",  // WoW (undead).
			"Zenith or Quasar?",  // IT Crowd.
			"100% Organic",
			"Roll the Dice",
			"Wizard in Training",
			"Radioactive",
			"I see Fractals Everywhere",
			"Rhyme of Duotime",  // Bard's Tale.
			"69, Dudes!",  // Bill & Ted's.
			"Reroll Often",
			"It's all relative",
			"We're all relative",
			"Use the Maths",
			"Use the Internets",
			"Kiss the Cook",
			"Buy Local",
			"Nerds do it Better",
			"Nerdy",
			"Geeky",
			"Geek chic",
			"I Love Aliens",
			"Try a Gargle Blaster",  // Douglas Adams.
			"Trust No One",
			"Truth is Out There",  // X Files.
			"Tastes Like Chicken",
			"Try the Clam Chowder",
			"I Believe",
			"How Does it End?",
			"Ask Me Anything",
			"I'd Rather be Flying",
			"My Other Bar is Clean",
			"Got Barley?",
			"Stay Awhile and Listen",  // Diablo.
			"Mathematical!",  // Adventure Time.
			"Algebraic!",  // Adventure Time?
			"It's Space Time!",
			"Boosh!",
			"Virtually Awesome",
			"Virtually There",
			"Virtually Anywhere",
			"Virtually Blind",
			"Virtually Certain",
			"Virtually Defined",
			"Virtually Everywhere",
			"Virtually Free",
			"Virtually Impossible",
			"Virtually Legal",
			"Virtually Normal",
			"Virtually Unstoppable",
			"Virtually Zero Calories",
			"Virtually Real",
			"Going Infinite",
			"So Mote It Be",  // Grand Masons.
			"Chatty Fellow, huh?",
			"Celebrity Chef",
			"Waste Not",
			"Operation Dinner Out",  // Sneakers.
			"Gone Meta",
			"Got Skillz?",
			"Beverage, Sir?",
			"As you wish",  // Princess Bride.
			"I Love Nuked Food",  // Twins movie.
			"Don't Rob Me Bro",
			"Resistance is Fungible",
			"Panic",
			"In It to Win It",
			"We Name Names",
			"You'll be Back",
			"Call me Betty",  // Song.
			"Reapers Fear Clones",
			"You Look Familiar",
			"Do I Know You?",
			"Ladies Night",
			"Happy Hour",
			"Leeroy Was Here",
			"3 Drink Limit",
			"4 Drink Limit",
			"5 Drink Limit",
			"6 Drink Limit",
			"7 Drink Limit",
			"8 Drink Limit",
			"9 Drink Limit",
			"Vote for Pedro",  // Napoleon Dynamite.
			"Who are you?",
			"What are you?",
			"Who was Maud, Anyway?",  // Nethack.
			"Vlad was Here",  // Nethack.
			"Hello, World!",  // Common programming phrase.
			"There is no Pie",
			"Reality is in Fact Virtual",  // No Fear poster.
			"Space is Big",
			"Space is Really Big",
			"Space is Really, Really Big",
			"It's a Small World",  // Disney.
			"All the World's a Stage",  // Shakespeare.
			"Nothing is Real",
			"Smoke You a Kipper",  // Red Dwarf.
			"I'm kind of a big deal",
			"Your Message Here",
			"Stellar",
			"No Soup for You",  // Seinfeld.
			"This Is My Drinking Pin",
			"Super Star",
			"Cosmic",
			"Brilliant",
			"Starlet",
			"I'm the Star",
			"Voted Scroob, Got Scroobed",  // Spaceballs.
			"2 Drink Minimum",
			"Never Give Up",  // Galaxy Quest.
			"Never Surrender",  // Galaxy Quest.
			"Loca Cola Coola",  // Duke Nukem?
			"Shaken or Stirred?",  // James Bond.
			"Expect Bugs",
			"Rockin Team Rocket",  // Pokemon.
			"Gone Relativistic",
			"Looking for Xenon and Borno",  // Starflight game.
			"Knowing is Half the Battle",  // GI Joe.
			"You Mad Bro?",
			"Haters Gunna Hate",
			"Visited Area 51",
			"Under New Management",
			"We Remodel",
			"X Marks the Spot",  // Indiana Jones.
			"X Never Marks the Spot",  // Indiana Jones.
			"Uber 1337",
			"Number Five is Alive",  // Short Circuit.
			"Pay Me Tuesday",
			"Come At Me Bro",
			"Hi, Mom!",  // LMFAO.
			"Would You Kindly",
			"Eugene, Chef Four",  // Star Trek (ish).
			"47",
			"No Take Candle",  // World of Warcraft.
			"88 MPH",  // Back to the Future.
			"Up to 11",
			"Age of Aquarius",
			"Flatland",
			"Do Eat",
			"Strange Matters",
			"Quarky",
			"Neutronium Rocks",
			"Parallel Universe",
			"I'm a Clone",
			"This is the World",
			"The Only World",
			"Fus Ro Dah",
			"Arrow to the Knee",
			"Bullet to the Knee",
			"Laser to the Knee",
			"Deja Vu",
			"E.T.",
			"Out the Door Dinosaur",
			"Come On In",
			"Try the Special",
			"Don't Eat the Special",
			"I'll Have the Special",  // Spaceballs.
			"I'll Have what It Has",
			"Need a Hand?",
			"Need Some Hands?",
			"Tip Big",
			"Constellation Prize",
			"No Sweat",
			"Off the Record",
			"24 Hour Diner",
			"24 Hour Drive Through",
			"Open All Golidays",
			"Pick up the Tab",
			"Put it on the Tab",
			"Buy me a Moon",
			"Send me to a Moon",
			"Open Rain or Shine",
			"Open Lightning or Lava",
			"Working Man's Man",
			"Working Woman's Woman",
			"Seeing Eye to Eye to Eye",
			"Under Construction",
			"Don't Mind the Mess",
			"Mind the Gap",  // Common saying, came to mind from X3: Threat.
			"As Seen on SETI",
			"It Just Got Real",
			"I'll be Back",
			"Show Me the Money",
			"Why So Serious?",  // Joker in Batman.
			"I Am Your Father",  // Star Wars.
			"I Am Not Your Father",  // Star Wars.
			"Have a Nice Chianti",
			"Soylent Green in Stock",
			"It's Soylent Green",
			"Soylent Green is Green",
			"Soylent Green is Aliens",
			"Time to Phone Home",  // E.T.
			"No Place Like Home",  // Wizard of OZ.
			"Hakuna Matata",  // Lion King (African phrase).
			"Zamina Mina",
			"I'm Afraid I Can't Do That",  // 2001 A Space Odyssey.
			"Piece of Cake?",
			"Cup of Joe?",
			"All Thumbs",
			"Dead Ringer",
			"Expert Negotiator",
			"Easy as Pie",
			"Food for Thought",
			"Cold Feet",
			"Go Dutch",
			"Half-baked",
			"Bad Taste",
			"Mint Condition",
			"Poker Face",
			"Killing Time",
			"Use Your Imagination",
			"Meet Me Halfway",
			"Money Talks",
			"Neck and Neck and Neck",
			"No.",
			"I'm a Cook, not a Psychic",  // Star Trek / bones (ish).
			"There can be Only One",  // Highlander.
			"Virtualize Whirled Peas",
			"Tissue? I Hardly Know You",
			"Donations Accepted",
			"You are Here",
			"Everything is Somewhere",
			"Drive Fast and Fly Low",
			"Take Me Drunk I'm Home",
			"Life's a Joke, Then You Die",
			"Life's Short, Buy a Drink",
			"I Saw That",
			"Be Excellent",  // Bill & Ted's.
			"Eschew Obfuscation",
			"Might Live Forever",
			"Living Forever",
			"Frog in Throat",
			"Right to Work",
			"Union Shop",
			"Non-union Shop",
			"I Love Tacos",
			"Call me Chumbley",
			"Thoroughly Thal",
			"What's That, My Boy?",
			"Reverse the Polarity",
			"Mmmm I Wonder",
			"The Tea's Getting Cold",
			"Fantastic!",
			"I'm Sorry.",
			"Bow Ties are Cool",
			"Hello I'm the Bartender",
			"We Can't Change History",
			"It's Elementary",  // Sherlock Homes.
			"Naturally Organic",
			"Well Defined",
			"Hand Waving",
			"Souls Look Upward",
			"The Final Frontier",
			"Made of Stars",
			"Beep... Beep...",
			"Magnificient Desolation",
			"Indistinguishable from Magic",
			"I Wonder Why",
			"Barn Star Winner",
			"Five Star Restaurant",
			"Four Star Restaurant",
			"Five Star Inn",
			"Four Star Inn",
			"Main Sequence",
			"Like a Star",
			"You're the Star",
			"Star Blazer",
			"All Star",
			"Rock Star",
			"Movie Star",
			"Star Struck",
			"All-star cast",
			"All-star game",
			"Star Crossed",
			"Space Aged",
			"Infinity and Beyond",
			"Space Cadet",
			"Space Camp",
			"Space for Rent",
			"Space Man",
			"Space, Man!",
			"Try the Space Nog",
			"Space Stud",
			"Public Space",
			"It Came from Outer Space",
			"Plentiful Parking",
			"I'm Complicated",
			"Open Space",
			"Quantum Space",
			"Space Race",
			"Semi-normal Space",
			"Don't Double Space",
			"Dinner MC",
			"Master Chef",
			"Amateur Chef",
			"Worldly",
			"Grade A Meet",
			"Sanitation Citation",
			"Pirates Kidnapped Wife",
			"Two Dimensional Personality",
			"Two Dimensional Characters",
			"Inconceivable",
			"No One of Consequence",
			"I Hope We Win",
			"Do We Win?",
			"Will We Win?",
			"Did We Win?",
			"Last Arthling?",
			"I see Weird People",
			"I see Drunk People",
			"UFO Nut",
			"I voted Frodo",
			"It's all Relative",
			"Violence Solves Nothing",
			"Refrigerator Raider",
			"Imba Nimby",
			"Imba by Design",
			"Another Day in Paradise",  // Oblivion movie.
			"Welcome, everything is fine!",  // The good place.
			"Space Isn't Flat",  // A 2D starmap isn't realistic.
			"Dimensions are Relative",  // But a 2D starmap can be just as good as 3D.
		],
		barPinPirate1: [
			"Arrr!",
			"Derp",
			"On Your 6",  // Army phrase.
			"Are We the Baddies?",
			"Arms for the Poor",
			"Arrrms for the Poor",
			"Finality",
			"I call wang",  // Deadpool.
			"Rogue Like",  // Nethack (ish).
			"Near Miss",
			"You Lost?",
			"Live Short and Plunder",
			"Bitcoin Mining Your CPU",
			"Blockchain Mining You",
			"Can't Stop the Pain",
			"Leather is Better",
			"Screaming Alpha Yet?",
			"Happy Hour Every Hour",
			"Life is but a Scream",
			"What Are You Lookin At?",
			"Tonight... You...",  // Aqua Teen.
			"Knowing is Half the Bottle",  // GI Joe (ish).
			"Tryhard?",
			"War is Hell",
			"Later Tater",  // 70's Show?
			"Who You Gunna Call?",  // Ghostbusters.
			"Cry Home to Mama",
			"Just Opened",
			"You Will Lose",
			"Try Soup on the Lamb",
			"Drunks Are Home",
			"Quit Your Day Job",
			"Too Cold",
			"Hey There, Space Sailor",
			"Game Foul",
			"Be Evil",
			"Stacked the Deck",
			"Shifting to Red",
			"Death to the Demoness!",  // Existenz.
			"Checkpoint Charlie",
			"40 to 1 and Counting",  // Douglas Adams.
			"Life is Pain",
			"Fear and Loathing",
			"Cereal Killer",
			"Tis But a Scratch!",  // Monty Python.
			"Shoot First",
			"Begone",
			"Killing Business",
			"Get Out",
			"Run Away",
			"Tuck Your Tail",
			"Flee",
			"Hit the Sky",
			"Hit the Belt",
			"Make Tracks",
			"Vamoose",
			"Scram",
			"Beat It",
			"Skedaddle",
			"Take a Hike",
			"Go away",
			"Cruel Hello, World!",  // Play on hello world.
			"Say Hello Little Friend",
			"Okay, I'm reloaded!",  // Common, came to mind from the Lonely Island song.
			"Well-done with a Side of Gun",
			"You Ain't That Lucky, Punk",
			"Regular or Extra Crispy!",
			"Leave an Address for Your Head",
			"Stewed Hero Gumbo",
			"Meet Billystick and Blackjack",
			"Bring Your Own Casket",
			"I'm Going Commando",
			"Check Out My Gun",
			"Destroy Him, My Robots",
			"Stay Awhile. Stay Forever",
			"This One is Mine",
			"Didn't Read Lol",
			"Techno Viking",
			"Rule 34",
			"Wrecking Bar",
			"Stick to the Bar Code",
			"**** ***!",
			"The B Team",
			"Keep Gawking, I'm Reloading",
			"Feeling Lucky, Punk?",
			"Beware the Full Moon",
			"Birds Sing, You Die",
			"Ends Justify Means",
			"Roasting Shubs and Zuuls",
			"Shub or Zuul?",
			"Right to Shirk",
			"First One's Free",
			"New World Order",
			"Run Away, Little Girl",
			"Need More Rage",
			"Dead Man Walking",
			"Back Up Often",
			"Shell Game?",
			"Zero Sum Game",
			"Con Game",
			"Guilty as Charged",
			"Natural Born Pirate",
			"Joined Dark Side",
			"Violence Solves Everything",
			"Just Ran out of Gum",
			"Go Big and Go Home",
			"Go Away",
			"Leave",
			"Keep What You Kill",  // Pitch Black sequel.
			"Sometimes Dead is Better",
			"Usual Suspect",
			"Surrender.",
			"To the Pain",
			"You Killed My Father",
			"Prepare to Die",
			"Undercover Cop",
			"Crooked Cop",
			"Taking Bribes",
			"Sharrrp Knives",
			"Digital Pirate",
			"Piracy is not Stealing",
			"Arrrmy of One",
			"Stellarrr",
			"Alarrrmed",
			"Arrrmed",
			"All-starrr",
			"Starrr struck",
			"Pool Sharrrk",
			"Hostile Harrrbor",
			"Rum Runner",
			"Arrrchduke",
			"Master Arrrchitect",
			"Beware Arrrchon",
			"Up 2 No Good",
			"Arrr u 4 Real?",
			"Arrr you Hungry?",
			"Arrr you Threatening Me?",
			"Arrrgonaut",
			"Arrristocrat",
			"Arrrmored",
			"Arrrrest No One",
			"Bullet to Arrrrm",
			"Laser to Arrrrm",
			"Arrow to Arrrrm",
			"Arrrrmed",
			"Arrrt Collector",
			"Arrrticulate",
			"Arrrtifact Hunter",
			"Welcome to the Barrr",
			"No Beggarrrs",
			"Bipolarrr",
			"Try the Caviarrr",
			"You look Familiarrr",
			"Farrr from Honest",
			"Grammarrr Nazi",
			"Irregularrr",
			"Wearing Kevlarrr",
			"Lunarrr Lander",
			"Nebularrr",
			"Gone Nuclearrr",
			"Well Below Parrr",
			"Postnuclearrr",
			"Prewarrr",
			"Bewarrr the Quasarrr",
			"Packing Radarrr",
			"Get it in Cellarrr",
			"Ask About My Scarrr",
			"It Is Crap",
			"Vulgarrr",
			"Warrr",
			"Yarrr",
			"Get Off My Lawn",
			"Viva la Resistance",
			"Bite My Cold Limp Tentacle",  // Futurama.
			"6 Drink Minimum",
			"12 Drink Minimum",
			"Ninja Looter",
			"You Killed My Brother",  // Red Dwarf.
			"Bullet to the Eye",
			"Arrow to the Eye",
			"Laser to the Eye",
			"Wuju Style",
			"Cooking E.T.",
			"Nom Nom Nom",
			"No One Hears You Scream",
			"I Hear You Scream",
			"Mad Mixer",
			"Take Your Money",
			"Tip or Double Tap",
			"Health Inspector Barbecue",
			"Tell Me if You're a Cop",
			"Space Bunnies Must Die",
			"Starvin' Marvin",
			"Need Breathing Space",
			"Space Base",
			"Disputed Space",
			"Space Cowboy",
			"Space Ghost",
			"Rogue Star",
			"Star Destroyer",
			"Star Cannibal",
			"Falling Star",
			"He's Not a Killer",
			"When I Say Run, Run.",
			"Elevate!",
			"Rob the Cradle",
			"Exterminate!",
			"Under the Table",
			"Lady Killer",
			"There Can be Only One",
			"Fight Crime: Shoot Back",
			"I'd Kill for a Drink",
			"Look out Behind",
			"Trust Everyone",
			"Enjoy Silence",
			"Learn to Enjoy Silence",
			"You Stuck on Stupid?",
			"Who's Your Daddy?",
			"Life Wasted on Living",
			"Live Tough and Die",
			"No Tap, Already Stolen",
			"Non-union Shop",
			"Stick to the Code",
			"Code? More Like Guidelines",
			"Ahoy!",
			"Ahoy Matey!",
			"Avast Ye Scoundrel!",
			"Aye!",
			"Aye Matey",
			"Aye Me Beauty",
			"I Tire of You",
			"Darn Bilge Rats",
			"Grog Fer Lubbers",
			"Ahoy Thar",
			"And a Bottle of Rum",
			"Rum Rum Rum and a Bottle of Rum",
			"Rum",
			"More rum",
			"Rum. Just Rum",
			"Death is Certain",
			"Just Rum Away",
			"Rum Away from Me",
			"Home Rum",
			"Rum From My Gun",
			"Dry Rum",
			"Fun Rum",
			"Hit and Rum",
			"In the Long Rum",
			"Milk Rum",
			"On the Rum",
			"Trial Rum",
			"Rum Along",
			"Rum you Down",
			"Rum of the Mill",
			"Rum on Sentence",
			"Rum Over You",
			"Rum Out of Time",
			"Training for Long Rum",
			"Family-rum Business",
			"Don't Rum Away",
			"Rum for the Money",
			"I rum This Store",
			"I'm Gunna Rum You Ragged",
			"Rivers Rum Red",
			"Naked Rum",
			"Overrum with Booze",
			"Red Rum",
			"Rum for the Border",
			"Rum for your Life",
			"Rum from the Future",
			"Rum Hard",
			"Rum Hit Wonder",
			"Rum into Debt",
			"Rum Through",
			"Rum like Hell",
			"Rum out of Booze",
			"Rum Rabbit Rum",
			"Rum Rampant",
			"Rum for the Hills",
			"Rum that by Again",
			"Rum with the Wolves",
			"Deeprum Tram",
			"State Rum Enterprise",
			"Another Rerum",
			"Annual Rumoff",
			"Blade Rummer",
			"Bombing Rum",
			"Bump 'n Rum",
			"Cool Rummin",
			"Donut Rum",
			"Hit a Home Rum",
			"Beer Rum",
			"Eat and Rum",
			"Midnight Rum",
			"Ninja Rum",
			"Pun Rum",
			"Six-mile Rum",
			"Smuggling Rum",
			"Taco Rum",
			"Training Rum",
			"Rum out of town",
			"Cannonball Rum",
			"Pirate's Life for Me",
			"Prepare to be Boarded",
			"Handsomely",
			"Ho!",
			"No Prey, no Pay",
			"Parley?",
			"No Parley.",
			"To Plunder",
			"Viking Incognito",
			"No Cake, Just Lies",
			"Space Legs",
			"Smartly",
			"Go Swab the Deck",
			"Mutiny it Be",
			"No Quarter",
			"Give no Quarter",
			"Black Jack",
			"Clap of Thunder",
			"Nelson's Folly",
			"To the Helm",
			"Hand Over Ye Booty",
			"Dead Men don't Talk",
			"Dead Med don't Walk",
			"Heave Ho",
			"Jolly Roger",
			"Salt an Old Salt",
			"Savvy?",  // Pirates of the Caribbean.
			"Walk the Plank",
			"Belay On",
			"Blow the Man Down",
			"To Davy Jones' Locker",
			"Fire in the Hole",
			"Speak Easy",
			"Time Bandit",
			"Definitely Dalek",
			"Rage Face",
			"Han Shoots First",  // Star Wars.
			"You die of dysentery",  // Oregon trail.
			"Here lies andy",
			"Peperony and chease",
			"Min Max Much?",
			"5318008",  // Boobies on calculator.
			"Fool Walks Into Bar",
			"Zerg 'Em",  // Starcraft.
			"What do you see??",  // Sunshine.
		]
	});
})();


