(function() {

  SU.addProps(ST, {
		barEnough: function(seed) {
      return ST.randText(ST.barEnough1, seed + 102.5) + ST.randText(ST.barEnough2, seed + 103.5);
		},
		barEnough1: [
		  "Seems you've had enough, ",
		  "That's quite enough, ",
		  "You planning on flying, ",
		  "Give me your keys, ",
		  "I think you've had enough, ",
		  "Time to go home, ",
		  "Closing time, ",
		  "Get out of here, ",
		  "Look at yourself, ",
		  "Get off the floor, ",
		  "You're pissed, ",
			"You be pissed, ",
			"You're stoned, ",
			"You're flying, ",
			"You're lit, ",
			"You're plastered, ",
		  "Cutting you off, ",
		  "Not on my watch, ",
		],
		barEnough2: [
		  "lass",
		  "dear",
		  "bub",
		  "squire",
		  "babe",
		  "doll",
		  "honey",
		  "princess",
		  "pumpkin",
			"kid",
			"tot",
		],
    barDrink: function(seed) {
        return ST.randText(ST.barDrink1, seed + 100.5) + ST.randText(ST.barDrink2, seed + 101.5);
    },
    barDrink1: [
      "Tap",
		  "The",
		  "The Doctor",
		  "Zaphod",
		  "James T.",
      "Sparkling",
		  "Seven",
      "Gummy",
      "Gummy Bear",
      "Gremlin",
      "Big Sky",
      "Blue Sky",
      "Purple Sky",
      "Mineral",
      "Carbonated",
      "Fruit",
      "Vegetable",
      "Strange",
      "Carrot",
      "Bovine",
      "Gim",
      "God",
      "Green",
      "Spring",
      "Dirty",
      "Ice",
      "Energy",
      "Egg",
      "Light",
      "Malt",
      "Dry",
      "Cherry",
      "Mild",
      "Pale",
      "Cabernet",
      "Pinot",
      "Vintage",
      "Boiler",
      "Mint",
      "Gin",
      "Flaming",
      "Brass",
      "Mai",
      "Jack",
      "Four",
      "Pisco",
      "Black",
      "Salty",
      "Gin",
      "Piña",
      "Long Island",
      "Iced",
      "El Toro",
      "Tonic",
      "Apple",
      "Screw",
      "White",
      "Jungle",
      "Whiskey",
      "Glen Tokyo",
      "Bush",
      "Earth",
      "Pink",
      "Green",
      "Blue",
      "Irish",
      "Bloody",
      "Snake",
      "Pan Galactic",
      "Barley",
      "Virgin",
      "Cola",
      "Coffee",
      "Ginger",
      "Hot",
      "Cold",
      "Milk",
      "Chocolate",
      "Strawberry",
      "Berry",
      "Soy",
      "Orange",
      "Root",
      "Bottled",
      "Scotch",
      "Corn",
      "Wheat",
      "Bourbon",
      "Rice",
      "Millet",
      "Buck",
      "Grape",
      "Perry",
      "Pear",
      "Poire",
      "Plum",
      "Apricot",
      "Pine",
      "Pineapple",
      "Juniper",
      "Banana",
      "Plaintain",
      "Hot",
      "Coconut",
      "Pomace",
      "Potato",
      "Sweet",
      "Sugar",
      "Palm",
      "Coyol",
      "Honey",
      "Brown",
      "Odd",
      "Cask",
      "Stock",
      "Oktoberfest",
      "Small",
      "Distilled",
      "Hard",
      "Weak",
      "1800",
      "Dos",
      "Avoin",
      "Cabo",
      "Voodoo",
      "Corpse",
      "Death",
      "Porch",
      "Paradise",
      "Oall",
      "Old",
      "Lime",
      "Lame",
      "Micky",
      "Royal",
      "Blue",
      "Dark",
      "Stormy",
      "El",
      "Fish House",
      "Fluffy",
      "Gun",
      "Jager",
      "Pain",
      "Planter's",
      "Staten Island",
      "Sun",
      "Ti",
      "Agent",
      "Cape",
      "Court",
      "Kremlin",
      "Red",
      "Rose",
      "Screw",
      "Intimate",
      "Missouri",
      "Rusty",
      "Three",
      "Wise",
      "Ward",
      "Cheeky",
      "Prince",
      "Ruby",
      "Mulled",
      "Baby",
      "Buttery",
      "Golden",
      "Grass",
      "Oatmeal",
      "Pink",
      "Quick",
      "Cream",
      "Wall",
      "Tomato",
      "Blueberry",
      "Screaming",
      "Common",
      "Snow",
      "Polar",
      "Redheaded",
      "Mango",
      "Jazmin",
      "Agua",
      "Shrub",
      "Cobbler",
      "Filtered",
      "Turkish",
      "Vienna",
      "Moloko",
      "Jello",
      "Liquid",
      "Purple",
      "Silk",
      "Surfer",
      "Wet",
      "Bahama",
      "Brave",
      "Grateful",
      "Tokyo",
      "Wedding",
      "Lavender",
      "Prickly",
      "Friday",
      "Raspberry",
      "Pomegranate",
      "Sierra",
      "Spiked",
      "Peach",
      "Maple",
      "Cupcake",
      "Blackberry",
      "Butterfly",
      "Rhubarb",
      "Pop",
      "Signature",
      "Edible",
      "Caramel",
      "Vanilla",
      "Tequila",
      "Syrup",
      "Soggy",
      "Flat",
      "Leeched",
      "Cucumber",
      "Clover",
      "Earl",
      "Almond",
      "Hazelnut",
      "Cannamon",
      "Wild",
      "African",
      "Pure",
      "Currant",
      "Breakfast",
      "Citrus",
      "Cranberry",
      "Decaf",
      "English",
      "Jasmine",
      "Lady",
      "Lemon",
      "Mixed",
      "Pepper",
      "Peppermint",
      "White",
      "Winter",
      "Fall",
      "Oolong",
      "Flower",
      "Cloudy",
      "Dragon",
      "Loud",
      "Whip",
      "Finger",
      "Big",
      "Oriental",
      "Loose",
      "Bright",
      "Dark",
      "Icy",
      "Smoky",
      "Woodsy",
      "Clean",
      "Boar",
      "Elephant",
      "Fish",
      "Fudge",
      "Canned",
      "Solid",
      "Unusual",
      "Rare",
      "Soft",
      "Smooth",
      "Mud",
      "Volcano",
      "California",
      "Grand",
      "Slippery",
      "Scottish",
      "May",
      "Victory",
      "Pony",
      "Laughing",
      "Clown",
      "Alamo",
      "Binge",
      "Sucker",
      "Churchhill's",
      "Buzz",
      "Duff",
      "Girlie",
      "Glen",
      "Jumbo",
      "Hammersteen",
      "Mudder's",
      "Panther",
      "Sumerian",
      "Shotz",
      "Uncle's",
      "Sailor's",
      "Monk's",
      "Allison's",
      "Heisler",
      "Booty",
      "Planet",
      "Bouncy",
      "Bubble",
      "Nuka",
      "Sunset",
      "Bonk",
      "Slug",
      "Butter",
      "Romulan",
      "Klingon",
      "Ent",
      "Muddled",
      "Vitality",
      "Mushroom",
      "Rabbit",
      "Happy",
      "Desperate",
      "Mad",
      "New",
      "Passion",
      "Orangatang",
      "Kiwi",
      "Morning",
      "Witch",
      "Fireside",
      "Cutie",
      "Vampire's",
      "Tropical",
      "Duck",
      "Cowboy",
      "Naked",
      "Dark Side",
      "Fantasy",
      "Suicide",
      "Serious",
      "Panda",
      "Top-Shelf",
      "American",
      "Angel",
      "Confederate",
      "Sting",
      "Gorilla",
      "One-Dash",
      "Rooster",
      "Barking",
      "Tiger",
      "Love",
      "Funky",
      "Apple Pie",
      "Altitude",
      "Bumble",
      "Candy",
      "Cement",
      "Fire",
      "Jelly",
      "Oil",
      "Pearl",
      "Prairie",
      "Southern",
      "Tootsie",
      "Gold",
      "Mage",
      "Moose",
      "Redneck",
      "Straight",
      "Absolute",
      "Sky",
      "Apparent",
      "Aurora",
      "Caldera ",
      "Celestial ",
      "Chaos",
      "Cosmic",
      "Double",
      "Doppler",
      "Dwarf",
      "Binary",
      "Elliptical",
      "Evolved",
      "Galactic",
      "Galilean",
      "Giant",
      "Globular",
      "Granular",
      "Hydrogen",
      "Hubble's",
      "Hydro",
      "Hydrostatic",
      "Inferior",
      "Irregular",
      "Jansky",
      "Kepler's",
      "Kirkwood",
      "Lagrange",
      "Lenticular",
      "Lunar",
      "Main",
      "Major",
      "Neutrino",
      "Neutron",
      "Newton's",
      "Nova",
      "Nuclear",
      "Oort",
      "Photon",
      "Plasma",
      "Proper",
      "Proto",
      "Quasi",
      "Radial",
      "Retro",
      "Right",
      "Roche",
      "Shell",
      "Solar",
      "Spiral",
      "Stone",
      "Super",
      "Tidal",
      "Ultra",
      "X-ray",
      "Sipping",
      "Yellow",
      "Zodiac",
      "Alpha",
      "Active",
      "Crusty",
      "Ion",
      "Jovian",
      "Trailing",
      "Airy",
      "Annular",
      "Metal",
      "Razor",
      "Arc",
      "Auto",
      "Blink",
      "Bucky",
      "Coma",
      "Comet",
      "Electron",
      "Gamma",
      "General",
      "Gas",
      "Igneous",
      "Infrared",
      "Ionized",
      "Jet",
      "Lost",
      "Milky",
      "Omega",
      "Parallax",
      "Planck",
      "Radial",
      "Scarp",
      "True",
      "Type",
      "Universal",
      "Van Allen",
      "Zenith",
      "Alien",
      "Asgard",
      "Betazoid",
      "Centauri",
      "Cryon",
      "Drell",
      "Elite",
      "Ewok",
      "Ferengi",
      "Yamato",
      "Grue",
      "Servant",
      "Martian",
      "Orc",
      "Protoss",
      "Predator",
      "Time Lord",
      "Ancient",
      "Higgs",
      "Mexican",
			"X",
    ],
    barDrink2: [
      " Eel",
      " Hat",
      " Boson",
      " Bugs",
      " Weevil",
      " in the Sky",
      " in Space",
      " at Rest",
      " at Sea",
      " Voids",
      " Void",
      " Universe",
      " Map",
      " Atlas",
      " Arm",
      " Tank",
      " Glass",
      " Class",
      " Acid",
      "olith",
      " Velocity",
      "rillion",
		  "bacca",
      " Centauri",
      " in Motion",
      " Mirror",
      " Double",
      " Fusion",
      " Way",
      "lensing",
      " Storm",
      " Month",
      " Group",
      " Pollution",
      " Cloud",
      " Chondrite",
      " Fashioned",
      " Mound",
      " Mount",
      " Relief",
      " Pupil",
      " Flux",
      "agraph",
      " Zero",
      "ometry",
      " Orbit",
      " Fault",
      " Wave",
      " Shock",
      " Time",
      "violet",
      " Remnant",
      "nova",
      "giant",
      " Cluster",
      " Flare",
      " Body",
      "real",
      " Limit",
      " Giant",
      "-Stellar",
      " Pulsar",
      " Perigee",
      " Nebula",
      " Meridian",
      " Belt",
      " Eclipse",
      "let",
      " Year",
      " Gap",
      " Lava",
      " Dynasty",
      " Plasma",
      " Parsec",
		  " Calrissian",
		  " Skywalker",
      " Lightyear",
      "kraken",
      " Kelvin",
      " Galaxy",
      "Meteorite",
      "opause",
      " Gravity",
      " Effect",
      " Finder",
      " Horizon",
      " Radiation",
      " Debris",
      " Corona",
      " Comet",
      "osphere",
      "shift",
      " Bang",
      " Unit",
      "bang",
      "cracker",
      " Point",
      "matter",
      "orama",
      " Feature",
      " Disk",
      " Quasar",
      " Roll",
      " Straight",
      " Floatie",
      " Floater",
      " Haze",
      " And Torture",
      " Lollipop",
      " Snapper",
      " Baron",
      " Slick",
      " Scientist",
      " Bean",
      " White",
      "balls",
      " Eraser",
      " Clot",
      " Birds",
      " Giraffe",
      " Paw",
      " Horse",
      " Spider",
      " Tail",
      " Chihuahua",
      " Vat",
      " Tears",
      " Cure",
      "ray",
      " Wings",
      " Psycho",
      " Psychic",
      " Candle",
      " Thorn",
      " Laughter",
      " Cough",
      " Farmer",
      " Crust",
      " on Fire",
      " Scout",
      " Cork",
      " Star",
      " Island",
      " Collar",
      " Ending",
      "fest",
      " Swill",
      " Draught",
      " Mug",
      " Potion",
      " Slurm",
      " Gurgleurp",
      " Bell",
      " Junk",
      "crocken",
      " Tantrum",
      " Synthehol",
      " Export",
      " Ambrosa",
      " Queen",
      " Glingue",
      " Bowl",
      " Slider",
      " Blush",
      " Brick",
      " King",
      " Leaf",
      " Mist",
      " Eyebrow",
      " Afternoon",
      " Blend",
      " Spice",
      " Calm",
      " Chai",
      " Gray",
      " Slushie",
      " Slush",
      " Creamer",
      " Shake",
      " Smoothie",
      " Rocks",
      " on the Rocks",
      " Soda",
      " Please",
      " Mojito",
      " Float",
      " Frosty",
      " Dictator",
      " Whiskers",
      " Dead",
      " Bull",
      " Mama",
      " Snack",
      " Slut",
      " Hooter",
      " Sunrise",
      " Shots",
      " Fart",
      " Mixer",
      " Job",
      " Plus",
      " Tux",
      " Brew",
      " Miel",
      " Crema",
      " Eye",
      " Tie",
      " Toddy",
      " Smash",
      "ball",
      " Cake",
      "mother",
      "father",
      " Slammer",
      "banger",
      " Slipper",
      " Doublet",
      " Dream",
      " Fix",
      " Squirrel",
      " Cookie",
      "hopper",
      " Nipple",
      " on the Beach",
      " 8",
      " Nail",
      " Horsemen",
      " Lancer",
      " Blazer",
      " Moon",
      " Lotus",
      " Tundra",
      " Mule",
      " Up",
      " Colonel",
      " Special",
      " Nights",
      "mother",
      " Cod",
      " Lagoon",
      " Shot",
      " Breeze",
      " pop",
      " Mary",
      "downer",
      " Ferry",
      "killer",
      "tee",
      " Cooler",
      "fire",
      " Volcano",
      " Critter",
      " Libre",
      " and Oil",
      " Hawaii",
      " Cup",
      " Mall",
      " Lady",
      " Slim",
      " and Tonic",
      " 75",
      "hound",
      " Century",
      " Fizz",
      "-de-galo",
      " Amigo",
      " Zombie",
      " and Jerry",
      " Sling",
      "car",
      " Affair",
      " Flip",
      " Orgasm",
      " Hulk",
      " Neck",
      " Connection",
      " Cocktail",
      " Daisy",
      " Manhatten",
      " Boot",
      "crawler",
      " Bomb",
      " Blood",
      " and Tan",
      " Gland",
      " Plus",
      " Reviver",
      " Tiki",
      " Julio",
      " Metaxa",
      " Soju",
      " Sherry",
      " Bock",
      " Liqueur",
      " Agave",
      "cane",
      " Berry",
      " Arak",
      " Sonti",
      " Brem",
      " Sorghum",
      " Pito",
      " Chicha",
      " Water",
      " Wine",
      " Grape",
      " Juice",
      " Sangria",
      " Vermouth",
      " Milk",
      " Drink",
      "nog",
      " Draft",
      " Lager",
      " Beer",
      " Bitter",
      " Porter",
      " Stout",
      " Pilsner",
      " Cider",
      " Mead",
      " Sake",
      " Limeade",
      " Lemon",
      " Ale",
      " Merlot",
      " Sauvignon",
      " Chardonnay",
      " Gris",
      " Riesling",
      " Champange",
      " Port",
      "maker",
		  " 9000",
		  "melt",
      " Martini",
      " Julep",
      " Daiquiri",
      " Sidecar",
      " and Tonic",
      " Fancy",
      " Monkey",
      " Tamagozake",
      "-Tai",
      " Rose",
      " Score",
      " Paradise",
      " Piscola",
      " Mimosa",
      " Sour",
      " Velvet",
      " Mimosa",
      " Dog",
      " Sour",
      " Mohito",
      " Colada",
      " Hurricane",
      " Codder",
      " Iced Tea",
      " Mocha",
      " Loco",
      "tini",
      " Kamikaze",
      "driver",
      " Russian",
      " Whiskey",
      "wacker",
      "quake",
      " Squirrel",
      " Vesper",
      " Blazer",
      " Moe",
      " Coffee",
      " Cosmopolitan",
      " Grasshopper",
      " Stinger",
      " Spritzer",
      " Margarita",
      "walk",
      " Mary",
      "bite",
      " Absinthe",
      "jack",
      " Calvados",
      " Gin",
      " Rum",
      " Tequila",
      " Vodka",
      " Brandy",
      " Scotch",
      " Gargle Blaster",
      " Cognac",
      " Kahlua",
      " Colada",
      " Cola",
      " Coffee",
      " Tea",
      " Horchata",
      " Chocolate",
      " Lemonade",
      " Nectar",
      " Punch",
      " Latte",
      "slime",
		  " Kirk",
      " Expresso",
		  " Jeffrey",
		  " Ahoy",
			" Kurt",
			" Khan",
			"mud",
			"X",
    ]

  });
})();


