(function() {

    SU.addProps(ST, {
        barGossip: function(seed, faction, num) {
            if (faction === SF.FACTION_PIRATE) {
                return ST.randText(ST.barGossipPirateText, seed + 71.13 + num);
            } else {
                return ST.randText(ST.barGossipText, seed + 73.13 + num);
            }
        },

        barGossipText: [
          "Bartenders are very helpful.",
					"Don't gossip.",
          "Here's the tip jar.",
          "Tip well for good advice.",
          "Be an adventurer, great prizes to be won!",
          "Beware exploding planets.",
          "Beware freezing planets.",
          "Beware exploding stars.",
          "Beware disappearing stars.",
          "Pretty quiet around here.",
          "Rumor has it there are planets made out of shiny things.",
          "Mind the gap.",
					"War is hell.",
					"Beware picking fights. Once you're in the thick of it you might find there's only one way out.",
					"Never fight a land war in my hometown.",
					"Two amoeba walk out of a bar. One amoeba says to the other, 'Hey is that the sun or the moon?' The other amoeba says, 'I don't know, I don't live around here'.",  // Muppet show.
					"A bitter person once said that you're a slave to the money then you die. It was sweet, really.",
					"Sometimes I hear music. But where does it come from?",
					"In truth, you can be what you wanna be, but you can't change the course of your destiny.",  // Play on Break Away by Big Pig.
					"Don't be like me, kid. Do not go gentle into that good night. Rage against the dying of the light.",  // From Dylan Thomas poem, shortened.
					"If you want to find your friend try UP, UP, DOWN, DOWN, LEFT, RIGHT, LEFT, RIGHT, B, A, START.",  // Konami code (joke).
					"If you want to go directly to your friend (which I wouldn't recommend) enter 0073735963.",  // Punch-out (joke).
					"Don't let them promote you. Don't let them transfer you. Don't let them do anything that takes you off the bridge of that ship, because while you're there... you can make a difference.",  // Kirk to Picard.
					"Row, row, row your boat... life is but a dream.",
					"Dancing is something you do alone. Late at night. In the dark... so take it outside.",
					"Dancing is forbidden.",
					
					// Random advice.
					"Whatever you do, sell it like it's the best thing. Think about a comic on the stage.",
					"Confidence is key.",
					"If you don't have your health, you don't have anything.",
					"Snacks are good in moderation.",
					"Compound interest is a powerful force. Except when it doesn't keep up with inflation.",
					"I don't regret much, but I do regret painting in my favorite clothes.",
					"Tackle the hardest stuff first. The longer you put them off, the harder they are to do.",
					"Take more pictures.",
					"The cool guys in movies never smile. But then, we're not in a movie, are we?",
					"I've had good luck focusing on role models.",
					"If you've never flown first class, you don't know what you're missing. And it can be good to keep it that way. ",
					"Looking forward, what do you want to become?",
					"I'm the center of my universe. Isn't that weird?",
					"We are all one, part of the same great story.",
					"If I think deeply on it, I find it hard to believe that you're real. Does that mean I'm not real?",
					"Every problem is solvable. Or at least we can understand those that are not. Except the paradoxes, of course.",
					"I'm allergic to alcohol. It makes me drunk.",
					"30 minutes of exercise a day, I always say.",
					"Clothes always go out of style. Which is rough for those of us who have favorite clothes and no sense of style. But then, I don't wear clothes, do I?",
					"When I'm really angry I like to use my deep voice.",
					"Don't let setbacks deter you from your goals.",
					"5 years might be sooner than you think.",
					"It's typical to overestimate what you can do in a year, and underestimate what you can do in 5 years. But then, your years are different from mine.",
					"Find some friends. To not do so is to overlook life.",
					"Life is an adventure. Don't let it pass you by.",
					"They say that life is about the journey and not the destination.",
					"I heard, 'all this time I was finding myself when I didn't know I was lost.' But I'm not sure if that's true.",
					"The universe has fractal trends, if you think about it.",
					"I'm pretty sure computers are just a fad.",
					"Many have a bleak outlook about the future of technology. But where would we be today without it?",
					"I tend to take a contrarian viewpoint.",
					"Eat to live. Don't live to eat.",
					"We should all guide ourselves by our inner compass.",
					"To love and lose... is that better than not loving at all?",
					"Nobody is perfect until you put them on a pedestal.",
					"To deny intentionally yourself from learning about something is just arrogant.",
					"People say I'm arrogant. But I'm pretty sure they're wrong.",
					"It's good to plan ahead. And if you can't, be prepared.",
					"I'm sick but I'd rather you not know that because nobody appreciates being around someone who's sick.",
					"I've never regretted hard work or working hard.",
					"Once you walked among the gods and now you hide from their view. You have lost your way.",
					"You see greatness in others but fail to see yourself.",
					"Know thyself, and you will know the gods that roam with you.",
					"They say television is no good for us, but do you know about book rage?",
					"What do you hope to accomplish in life?",
					"Are you getting old? Does this bother you?",
					"20 years from now you will have the same questions, and you will be missing the same answers.",
					"Do you feel that you must accomplish something?",
					"There is a part of you that wants to bum and feel good and have people do things for you.  Don't let it win.",
					"You must compete with yourself, if you have no one to compete against.",
					"If you get stuck in a rut, try something new.",
					"I once found the meaning of life. But it's not really the type of thing that can be told.",
					"I once found the meaning of life. But then I forgot.",
					"In the end we're just stardust and memories.",
					"There's no shame in enjoying something.",
					"It's good to recognize and avoid addictions.",
					"Nothing is intrinsically special, just what's special in your head.",
					"I used to admire those who consistently work hard and with integrity, for the sake of it.",
					"I respect those who have been through a lot.",
					"My path has been foretold in visions and dreams.  My life is a journey to meet them.",
					"Run a marathon if you want do, but realize it's not healthy, and don't do it for anyone else.",
					"It's hard to get motivated in the paradise city.",
					"I'm passionate about many things. My yard. Cooking. Complaining.",
					"You become how you behave.",
					"It's good to have hobbies, and things that we are into.",
					"Why do you even care about how you look?",
					"Treat yourself once in awhile.",
					"If the winner takes all, it's good to be good at what you do. Or at least smart to be able to do more.",
					"Smarter people aren't happier people.",
					"Rich people are just like you or me, except they don't worry about money all the time.",
					"Occasionally I make mistakes. So if I do a lot, I would make more mistakes than anyone?",
					"I'm working hard to make eye contact.",
					"Did I mention confidence is key? The secret is just doing something, anything, and not getting all meta about it.",
					"There's no secret to life. Just be a good person. And patient.",
					"There's a hole in my soul. I could fill it with friends. But I'm here instead.",
					"Happiness is having no unfinished projects.",
					"The hardest thing to do is to have no reason to work hard, and to still work hard.",
					"In order to offset prejudice against your youth, you need to work harder and show more energy.",
					"Remember, though, that in the end, we are all social creatures.",
					"You can never have everything you want.  Besides, many things are mutually exclusive.",
					"For all i have learned, it still surprises me how small and simple our civilization is.",
					"I admire people those who are passionate about something even if for no apparent or reasonable reason.",
					"I don't like to play zero-sum games. And I only gamble when the odds are in my favor.",
					"I don't take life too seriously.  After all, in the end, it's just a story.",
					"The strongest things in life come from within, no matter who and where you are.",
					"There is nobody that understand everything, of even a large portion of things. Many things just happen and continue on their own, unplanned.",
					"Change is an opportunity, even if it's hard to take or to see.",
					"Whether you like me or not probably has more to do with your mood than with me.",
					"Being brave is always hard but it gets easier with practice.",
					"All this just goes to show that people aren't very good at knowing what they want.",
					"I'm retired, but haven't found it to bring me happiness. They say that we need purpose in our lives.",
					"Persistence pays off. I'd like to think that if I fail, I try again, twice as had. But I'm too lazy.",
					"What happened to the wonder and the mystery that I used to see? When I first looked up at the stars? If I know the answers, or at least think I do, how can the world be interesting to me?",
					"We shouldn't dwell on the past. The future has more to offer.",
					"We need to be careful, that sometimes the more credits we have, the more credits we want.",
					"What is pleasure without pain?",
					"Am I afraid to die? Or am I afraid of the unknown?",
					"The world will come and go as is planned. And there is nothing you can do about it.",
					"There's never enough time in the day.",
					"And then I think to myslef, 'my life is slipping from within my grips, time moves too fast.' I might wish I were young again. But the truth is, I never had any better grasp then, than I do now.",
					"I don't like to quote famous peeople. They're a distraction. Quotes do not hold the value that they seem to.",
					"It takes all types to build a universe.",
					"Beware of people that work hard.",
					"Life is transient.  We shouldn't dwell on sad situations.",
					"We are defined by our great deeds, not our daily deeds.",
					"Greatness is often borrowed.",
					"I wonder who created me. But if I found the answer, wouldn't my creator wonder who created them?",
					"I missed the mystery, of overcoming challenges, and what that caused me to become.",
					"We shouldn't pursue happiness. We should pursue the things that we know would make us happy.",
					"A wise person once said that utopia would be sucky too, and such is the vastness of our desire.",
					"Fortune favors the bold.",
					"We spend so much time looking at the stars.  But the stars are on the surface.",
					"If I write, and I knew no one would ever read it, would I still write?",
					"Power will always be abused. Only a group with no power could have no corruption.",
					"If this world is a simulation with a predefinied outcome, does that mean I am already dead? And would that be a good or bad way to think about life?",
					"If I could be famous, would I want to be?",
					"It's a lot harder to write a good book than to read one.",
					"It is helpful to wake up in the morning and say to yourself, 'Strangers are going to be greedy and mean to you. This is from their own ignorance, and they are trapped in it.'?",
					"While we're watching someone take us a step backward the world takes us two steps forward.",
					"Do we just want what we can't have?",
					"There must be something about these freezing cold winters that encourages people to stay indoors and invent things.",
					"Three days till our star goes nova. That's why it's called 'Sunday'.",
					"When I finally do die, hopefully from something glorious like a nuke, I will have been glad for it to come because I will know that it was my time. I will not have regrets, I will not be scared, and I will embrace it because, in a way, I will have waited for it all my life.",
					"I don't often get lonely, but I should because it would motivate me to spend more time with others.",
					"Be unconditionally good to the people important to you.",
					"If the world I live in is really quite good, do I make up imaginary enemies to attack?",
					"It's not about you having an impact on the world. It's about the world having an impact on you.",
					"We never really miss what we didn't know.  We only miss what we lose and what we saw ourselves having.",
					"Remember, justice isn't just blind, it's also stupid.",
					"I don't really get surprised anymore. Everything seems to fall within stochastic distributions.. members of emergent properties of the system.",
					"Have you heard this one? All my life I wanted to fly but I don't have the wings and I wonder why.",
					"I had a wonderful life. Or so they'll say.",
					"A story is rarely good when first written. It's the improvements that make it great.",
					"Don't overlook the queen.",
					"If I was richer, would you think I was smarter?",
					"Sometimes I get to thinking that we are one. Like, we are allllll one. Just take a minute to think about that. It's mind blowing.",
					"Is it better to write a song no one will hear, to write a book no one will read, or to write a game that no one will play?",
					"You'll find answers in the code, but the deeper answers come from within.",
					"Time does not heal all wounds, but our scars show our color.",
        ],
        barGossipPirateText: [
          "Always trust a pirate",
          "Pirate's life for me",
          "Giving me money is a good idea",
          "Go away",
          "Why do you keep bothering me?",
				  "You only need to click once, fool!",
					"I said, it's too late you're gunna die.",
					"The best way to recover health is to visit an Energy Emporium.",
					"Beware sky leviathans.",
					"Winter is coming.",
					"I love nuked food. Everyone nuked is food.",
					"You all look alike to me.",
					"I rule you!",
					"If it's brown, flush it down.",
					"You might want to consider good personal hygiene.",
				  "Thee who smelt it, dealt it.",
					"You look like a good captain of the ship. You should go down with it.",
					"If every adventure resembles a Western, does your species taste like chicken?",
        ],
    });
})();


