(function() {
  // reminder to use 'We' instead of 'I'. Maybe capitalize?
  // Obsolete categorizations: 1=weapon, 2=shield, 3=engine, 4=sensor, 0=any.

  SU.addProps(ST, {
    artifacts_text: [
      [0, "Filler", ""],
      [0, "Filler", ""],
      [0, "Filler", "Now vegan, and even more filling"],
      [0, "Stone of Triumph", "Woohoo!"],  // Simpsons.
      [0, "Severed Arm", "Etched in its skin: U=BTL"],  // Red dwarf.
      [0, "Flux Capacitor", "Traveling at 88 MPH"],  // Back to the Future.
      [0, "10097 32533", "76520 13586 34673 54876"],
      [0, "Eye of Agamotto", "One of three, obviously."],  // Marvel universe.
      [0, "A Cage", "If you die in a cage We win a bet"],  // Variation on a Rick&Morty joke.
      [0, "Jewel of Idahocales", "Useful for levitating food"],  // Aqua Teen Hunger Force.
      [0, "Genesis Torpedo", "aka The High-Velocity Bible"],
      [0, "Frog of War", "Undesirable, but necessary"],
      [0, "Ansible", "Answerable at a distance, not that We ever would"],  // Device in Ender's game and other science fiction.
      [0, "Ender's Mind Game", "Appropriately named"],  // Ender's game.
      [0, "Sword of a Thousand Truths", "Just a USB stick"],
      [0, "Loc-Nar", "Spontaneously plays rock music"],
			[0, "MCU Movies", "For anyone looking for a better story"],  // Because games aren't (usually) known for their plots.
      [0, "ET for Atari 2600", "A lesson for those under pressure"],
      [0, "Red Balloon", "A souvenir for what's to come"],
      [0, "Sinatra's Hand", "Now everyone can shake Sinatra's hand"],
      [0, "Hunter2", "It's your password"],
      [0, "Science Fiction Trope", "We're going with Alien Artifacts, for this one"],
      [0, "Dyson Sphere", "About the size of a bouncy ball. For now."],
      [0, "Horses", "Horses are the future of space travel. Horses and pubs."],  // Firefly / Serenity.
      [0, "Six-fingered Glove", "Hello. Our names are Inigo Montoyas."],  // Princess bride.
      [0, "The Dao of Hoy", "High-impact meta philosophy"],  // Game author's family names.
      [0, "The Bow of Bowen", "Stubborn and beautiful"],
      [0, "Anastasia's Angon", "a.k.a. The Destroyer"],
      [0, "Allegra's Aklys", "Amentum appended"],
      [0, "Acadia's Arcknife", "Sharp and shrill"],
			[0, "Five Lights", "We are glad you see the five lights. Next they'll be fingers."],  // ST:TNG "Chain of Command", itself an homage to 1984.
      [0, "Peace Lily", "You could use one. But without the lily."],  // Hot Fuzz.
      [0, "PolyGlot", ""],
      [0, "Plague Doctor Mask", "Made in Kentucky"],  // Because it's medieval.
      [0, "^(?:(?:(?:0?[13578]|1[02])", "A cat walking over a keyboard... or maybe what the fox says"],  // Some sort of regex probably from stack overflow. Forgot what this was the beginning of. Date validation maybe?
      [0, "Mega Seeds", "We're gunna need you to do Us a solid..."],
      [0, "Link's Recorder", "bum bum bum..... bada bum"],
      [0, "Power Bracelet", "Incredibly powerful and dangerous... if you're a boulder"],
      [0, "Rotor Zwerg", "Stoke me a clipper"],  // Red dwarf (in German).
      [2, "Zune", "We heard everyone on Earth is listening to them"],  // MCU.
      [0, "415-348-7910", "A mysterious message"],  // From Starflight.
      [4, "Hypercube", "A piece of history, lost in history"],
      [3, "Reticulating Splines", "Maybe they're your splines"],  // SimCity.
      [3, "Strange Doll", "You are a terrible person"],  // Terraria.
      [4, "Super special food seasoning", "Ingredients: salt"],
      [4, "Degauss Button", "We're hoping that you're Gauss"],
      [1, "Shark Sandwich", "With a tornado cola"],
      [4, "Paradoxical Tautology", "Courtsey Hanka Robotics"],
      [4, "Crotchless Uncle Sam Costume", "And your father"],  // Rick & Morty.
      [3, "Meeseeks Box", "Just to keep it simple"],  // Rick & Morty.
      [2, "Bones of Doug McClure", "Watch out for dinosaurs"],  // Red dwarf.
      [1, "Fleshreaper", "These things are known to happen"],
      [4, "Blogofractal", "Pretty much explains itself"],
			[2, "Scarecrow", "Oh sure, We've all been the scarecrow"],  // ST:TNG.
      [1, "Ball & Chain", "We feel like it's attached to Us"],
      [4, "X-Files", "Surely it was swamp gas"],
      [4, "Photographic Memory", "Also known as a camera. And it's already obsolete"],
      [3, "Heisenbug", "Drowned in beer"],
      [4, "Search Engine", "Only searches for one thing"],
      [3, "Kitchen Sink", ""],
      [4, "Cochleus Rift", "aka earbuds"],
      [3, "Quantum Flavordynamics", "It's a weak force"],
      [2, "Hot Cocoa", "Marshmallow included"],
      [3, "Truffula Seeds", "It's all We'll have left, at the rate you're going..."],  // Dr. Seuss.
      [4, "Cybernetic Implants", "Klaatu barada nikto"],
      [4, "Dead Parrot", "Or snuffed, croaked, offed, departed... whatever... you'll meet them all"],  // Monty Python.
      [1, "Rodent of Unusual Size", "We don't believe they exist"],  // Princess Bride.
      [1, "Tandy Raptor Jesus", ""],
      [4, "Gnomish Alarm-o-Bot", ""],  // WoW.
      [2, "Nightseam Coronet", ""],
      [3, "Driver's License", ""],
      [0, "Munchkin Cards", ""],
      [2, "Croydon Facelift", ""],
      [4, "An Occult Hand", ""],
      [3, "Ring of Gyges", ""],
      [3, "Chrono Trigger", ""],
      [1, "Thunderdome", ""],
      [3, "Jigawatts", ""],
      [3, "Pizza & Beer", ""],
      [4, "Murphy's Law", ""],
      [3, "Newton's Fourth Law", ""],
      [3, "Star Sail", ""],
      [3, "Sky Sail", ""],
      [3, "Lightcycle", ""],
      [0, "Infinity Stone", ""],
      [3, "Mailing Label", "So We know where to send your body"],
      [4, "Cell Phone", "So you can call your mama"],
      [1, "The Big One", "We felt creative when naming it"],
      [1, "Finishing Move", "For virtual kombat"],
      [3, "Geocore", "Also known as a rock"],
      [2, "Macaroons", "From a Brazilian tree"],
      [3, "Time Warp", "Let's do that again"],
      [3, "8-Bit Cartridge", "To match its 2-bit player"],
      [2, "Red Rum", "Mirror included"],
      [1, "Broken Childhood", "We just looked at your life and worked backwards"],
      [2, "Cyanide pills", "We expect you will need these soon"],
      [4, "Bones", "He's dead, Jim"],
      [2, "Dinglehopper", "An aesthetically pleasing configuration"],
      [4, "Therapist", "No, you misread it"],
      [3, "Deepsea Challenger", "Collywobbles included"],
      [3, "RMS Titanic", "Coincidentally your maiden voyage, too"],
      [3, "Enterprise", "And filled with capitalist pigs, eh comrades?"],
      [1, "Kaumodaki", "Or gada, mace, whatever... it's still just a club"],
      [2, "Sock Garden", "And sentient"],
      [2, "White Room", "Better bring a compass"],
      [4, "Cavity Magnetron", "Easily smuggled"],
      [1, "BBS Server", "Inflicts burning butthole syndrome"],
      [1, "Buzz Lightyear", "Virtually yours"],
      [3, "Time", "How can you have it, if you don't make it?"],
      [2, "Peach Trees", "Don't tell Mama"],
      [4, "Manual Override", "100 pages in length, and each one poorly translated"],
      [3, "Thermal Core", "The sky is a series of tubes"],
      [1, "Aether", "Literally, nothing. Roughly what We hope you become"],
      [3, "Portal Device", "Don't worry... the odds of your imminent death are very low... sometimes... maybe We should get our story straight, you monster"],
      [1, "Grabthar's Hammer", "Never give up! Never sunder!"],
      [1, "Dentist Sucky Straw", "Now you can't eat for thirty minutes"],
      [3, "Headlight Fluid", "Can only be purchased from the store in Bloody Gulch"],
      [3, "Elbow Grease", "Can you fetch Us some more?"],
      [3, "Glass Elevator", "It can fly every which way, except where you want to go"],
      [2, "Trout Farm", "Welcome to the Trout Farm"],
      [1, "Yakuza Hit Squad", "You're in good company"],
      [4, "Red Shift", "Widely misinterpreted to show that the universe is expanding, when actually We are all shrinking"],
      [1, "The Special", "It pops aliens out of people's stomaches, it makes organic weaponry... but what makes it so special?"],
      [1, "Black Ooze", "Fell in love with Tasha Yar, or rather, she fell for him"],
      [3, "Gummy Bear Juice", "Instructions: drink me for a fantastic trip... marketed to children"],
      [4, "Stem Cells", "Science, Technology Engineering and Math... also known as gray matter"],
      [4, "Think Tank", "Looks more like a fishbowl with those egos in it"],
      [2, "Lab Coat", "White, with a size of crazy"],
      [3, "Vista Cruiser", "Turns out, it was already flying high"],
      [3, "Incredible Machine", "You can call it Tim"],
      [3, "Rube Goldberg Machine", "It keeps going, and going"],
      [2, "Chronoton Fountain", "Don't mess with that. Don't mess with that."],
      [3, "Unmarked White Van", "What happens in the Solar System stays near the Orion Nebula"],
      [4, "Cryptocurrency", "In the final analysis, its only real value was in seeing who would steal it"],
      [4, "IQ Test", "Results look dim, but you can always blame it on space-bias"],
      [3, "Ice Box", "Full of strange creatures, freeze-dried"],
      [2, "Sleeping Cap", "Red, with a tassel"],
      [3, "Escape Velocity", "Best_band_ever"],
      [2, "Backhair Rug", "Brought to you by Veridian Dynamics"],
      [1, "Laser Disc Player", "Closely followed by laser eye surgery"],
      [3, "Betamax", "The one and only"],
      [2, "Fuzzy Dice", "For a really, really classy cockpit"],
      [3, "Elemental Water", "When you're underwater do you get wet, or does the water get you instead?"],
      [1, "Ancient Spell", "Well, Wicca isn't for everyone"],
      [2, "Trap Door", "You're the boss, got the button"],
      [4, "Secret", "If you knew what it was, it wouldn't be a secret"],
      [1, "Ghostbusters Trap", "You looked at the light"],
      [2, "Calabi-Yau Manifold", "K3 surfaces, quintic threefolds and brandworlds all tightly wrapped in string, in theory"],
      [3, "Ouroboros Batteries", "They keep going, and going, and..."],
      [1, "Manaflare", "Half-awesome, half-fake"],
      [3, "Bag of Small Rocks", "Useful for floating on water"],
      [3, "Mr. Roboto", "Nani o miten da yo Mr. Roboto"],
      [3, "X-TREME Graphics Card", "Ultra-fast 2D acceleration, simulated 3D"],
      [4, "Cochlear Implant", "More like a wet willy"],
      [1, "Gauntlets of Strength", "Too bad they're not Guantlets of Something Useful for Space Adventurers, but still throwable"],
      [1, "Starflare", "Anyone can use, STFL not STFU"],
      [1, "License to Kill", "Cetainly won't change your behavior, but at least you'll feel better about it"],
      [1, "Your Gun", "This is your gun... there are many like it but this one is yours"],
      [4, "Ouija Board", "Rhymes with squeegee board"],
      [4, "CA-53W", "Bonus points for hoverboard combo"],
      [4, "X-Ray Glasses", "Swindled again..."],
      [2, "Used Platemail", "The original share ware"],
      [1, "Silhouette of a Gun", "Can be shot six times at someone on the run"],
      [1, "Tiddlywinks", "Wink wink, nudge nudge, what more can be said?"],
      [1, "Pogs", "Portable, overhyped discs"],
      [2, "Full Metal Jacket", "Swiss-made, Texan championed"],
      [1, "Honeypot", "It's a trap!"],
      [3, "Quantum Slipstream Drive", "You keep dropping it"],
      [1, "Tooth and Nail", "Those who lost only thier teeth and nails were considered lucky, those who collected them... something else"],
      [1, "Secret Weapon", "Be advised: if you release the secret weapon, We start a subbuteo finger dance"],
      [4, "Wristwatch", "Set 15 minutes ahead"],
      [1, "Dreamliner Batter", "Yes, it's a weapon"],
      [3, "Shiposaurus", "Half spaceship, half dinosaur, and half awesome"],
      [3, "Covered Wagon", "For those long trips to the Oregon System"],
      [1, "Fuzz Bomb", "Looks a lot like a TV"],
      [1, "A-Bomb", "Hakuna matata, what a wonderful phrase"],
      [1, "Japanese Toilet", "G'day, bidet"],
      [1, "Tesla Coil", "Resonantingly remrofsnart"],
      [4, "Tesla Sphere", "Caution: do not use in combination with a tinfoil hat"],
      [1, "Hantavirus", "Rats... just rats"],
      [1, "Scythe of Erasmus", "Whoa, what was that?"],
      [4, "Virtual Library", "Shhhh...."],
      [4, "Write-only Memory", "Forgive and Forget"],
      [1, "Multiball", "Hard to find a good pinball machine these days"],
      [4, "Hints and Allegations", "And you can call Us Al"],
      [2, "Fast Twitch Muscle Fiber", "We can rebuild it, We have the technology... and the beat"],
      [1, "Desert Eagle", "A famous weapon named in honor of Deagle, the reclusive road warrior"],
      [2, "Prank Can of Farts", "Thee who smelt it, dealt it"],
      [4, "Big Can of Whoop", "Seems like a big deal"],
      [4, "Can of Worms", "Useless and nearly as confusing"],
      [3, "Gradient Bright 3", "An outdated model, but still great for catching thermal cores"],
      [1, "WMD", "Silent but deadly"],
      [2, "Whoopee Cushion", "Functional and comfortable"],
      [4, SF.GAME_NAME, "The latest trend in meta game development, it gets released before it's even finished!"],  // Spaceballs.
      [3, "Sense of Wonder", "You lost it once, don't lose it again"],
      [3, "Purple Goo", "Much better than Grey Goo, depending on your perspective"],
      [1, "Grey Goo", "Invented by Wil Wheaton"],
      [1, "Burn Notice", "Don't worry, nobody takes these things seriously"],
      [4, "Y Combinator", "Totally functional"],
      [1, "Nekrataal", "Turns out you might not want to protect them, either"],
      [1, "Big Book of War", "Could use it as a shield, but you don't really want to hang onto it"],
      [2, "Art of War", "Blah blah blah and something useful about spies"],
      [1, "Miniature Killbot", "We can always build more killbots"],
      [2, "Smoke and Mirrors", "It's all smoke and mirrors"],
      [3, "Kerjigger", "Close cousin of Thingamajig"],
      [2, "No Fear Poster", "Don't let your fears... err, yeah"],
      [4, "Cowbell", "Somehow never enough"],
      [3, "UFO Keys", "Left above the visor"],
      [1, "St. Elmo's Fire", "Huh, it really is fire... We always assumed that was just a figure of speech"],
      [3, "Roter Zwerg", "Even the creators weren't quite sure what they had invented, they just knew it was a hit"],
      [3, "Infinite Improbability Drive", "Chances are you will never find another - about the same chance of things getting back to normal"],
      [2, "Yellow Hat", "Not terribly powerful, but by George, quite a curiosity"],
      [1, "Giant Deathworm", "Frequently confused with mail"],
      [1, "Norn Frost", "Maximum overload!"],
      [3, "Snibbet", "It's a kind of plange"],
      [1, "Mercury Hammer", "Built one myself once, but it wasn't nearly this big"],
      [2, "Shrubbery", "IT is a good shrubbery, but now you must find another"],
      [1, "Red Herring", "Roughly as useful as a can of worms, or Chewbacca on the legal team"],
      [1, "Finger of Death", "Hard to say if it lead to their death or if it came from their death"],
      [2, "Oversized Chainmail", "Made for a creature of giant proportions, odd how you found it in a small European backpack"],
      [3, "Blue Slushy", "The best part is every time you visit an ice planet, it re-freezes!"],
      [4, "XBox Zero", "Finally got to the right number"],
      [4, "Oculus Rift", "The best named machine, period"],
      [3, "Duke Nukem Forever", "Once vaporware, now spaceware"],
      [2, "Immovable Object", "Shame you can't bring it with you"],
      [1, "Unstoppable Force", "Yes, it can't be stopped, but it's also really, really small"],
      [2, "Dinosaur Bone", "Meglosaurus, from the looks of it"],
      [2, "Void", "In space The Void is almost everywhere, but it's still nice to have a souvenir"],
      [4, "Wayback Machine", "But who would want to go back there?"],
      [1, "Claptrap", "And it won't shut up"],
      [4, "Dead Pixel", "Killed in a famous duel"],
      [2, "Piece of Resistance", "Viva La Résistance!"],
      [1, "Kragle", "Careful, it can get everywhere"],
      [2, "Plot Armor", "Infused with a healthy dose of drama power"],
      [2, "Red Shirt", "With a broken nametag attached, '#6'"],
      [3, "Solar Surfboard", "No, it's not silver"],
      [2, "Good Book", "Best choice for anyone looking for a good plot or multidimensional characters"],
      [2, "King Tut's Headdress", "Looted again and again and eventually looted by aliens"],
      [4, "Graph Paper", "Always handy, especially if lacking automap"],
      [3, "Bass Amp", "We built this city on rock & roll"],
      [2, "Red Flag", "It's from a revolution, We suppose"],
      [3, "Terror Drome", "Not as terrible as it sounds"],
      [3, "Nautilus", "20,000 leagues makes for a really, really deep sea"],
      [4, "Ziggy", "Sam, I'm going to need you to step into the airlock... trust me on this"],
      [3, "Damp Squid", "Always better damp"],
      [4, "Enchiridion", "Because when you're king of the galaxy, you'll need to know how to kiss a princess"],
      [1, "Zombienato", "A plastic water bottle that you can spin to make a tornado. It's filled with tiny plastic sharks, except they're zombies"],
      [3, "Argo", "Astronaut? Or Argonaut? Or Dancer?"],
      [4, "Book Of Thoth", "Should have burned at Alexandria"],
      [3, "Cintamani Stone", "WARNING: wishing for more wishes usually transforms the holder into a djinn"],
      [3, "Bumper Sticker", "You break for nobody, apparently"],
      [2, "Iodine Pills", "Best to stock up before they sell out"],
      [1, "Lævateinn", "All battle boils down to throwing sticks, if you think about it"],
      [4, "Smoking Mirror", "Looks like stars and nebulae, but probably just more smoke"],
      [4, "Jade Emperor", "Comes in amethyst, too, but that would be no good for your journey"],
      [2, "Peaches of Immortality", "Yes, peaches. And they're still fresh"],
      [2, "Yata no Kagami", "Thought to have burned in a shrine, actually stolen to play space tiddlywinks"],
      [2, "Golden Fleece", "Turns out gold isn't all that rare"],
      [3, "Chariot of the Sun", "Shame it only visits the one star"],
      [3, "Ra's Solar Barge", "So slow that the gates were a step up"],
      [3, "Flying Carpet", "A bit redundant, #1 interior decorator recommended"],
      [3, "Ǒusībùyúnlǚ", "Built for cloud hopping"],
      [2, "Robin's Staff", "A quarter the size, but it's more about how you use it"],
      [1, "Cupid's Bow", "After meeting the locals, you decide it makes a better decoration"],
      [1, "Singing Sword", "And it won't shut up"],
      [1, "Sudarshana Chakra", "Possibly the eigth chakra"],
      [1, "Death's Scythe", "A double-edged blade, so to say"],
      [2, "Wynebgwrthucher", "Arthur couldn't pronounce it, either"],
      [1, "Tizona", "El Cid started in Spain, and ended in space"],
      [2, "Aegis", "Temporarily on loan"],
      [2, "Helm of Darkness", "Similar to a certain cloak, but far more original"],
      [2, "Megingjörð", "Mighty stylish, but who wants to wear a girdle?"],
      [2, "Perseus' Shield", "Hard to take your eyes off"],
      [3, "Trojan Horse", "Best to look inside first"],
      [3, "Achilles' Heel", "No good for Achilles, now for two reasons"],
      [1, "Sword of Damocles", "Missed by a hair"],
      [2, "Gladiator Mask", "Also useful for Halloween"],
      [3, "Hypnorims", "One-size-fits-all rims for any spacefaring vehicle. They are retro and obnoxious; yet you have an odd compulsion to install them."],
      [1, "Yo-yo", "Ho-ho ho-ho and a bottle full of rum-rum"],
      [4, "Artifact Compendium", "Over a thousand pages but no pictures to be found"],
      [2, "Plastic Dome", "One-size fits all stolen UFOs"],
      [4, "Scout Handbook", "Be prepared"],
      [1, "Laser Pointer", "I looked at the trap, Ray!"],
      [4, "Requisite Probe", "Huh, your ship already has one"],
      [4, "Golden Compass", "Fool's gold, actually"],
      [4, "Jack's Broken Compass", "Yo ho ho!"],
      [2, "Half-baked clone", "Give him 20 min in the dark and he'll be fully baked"],
      [3, "Holly Hop Drive", "Sends the ship to another dimension. One where Ringo was a really good drummer."],
      [2, "Central AC", "Has a lot of fans"],
      [3, "Delorian", "3032 called... and it wants its time travel joke back"],
      [1, "Pinch", "Way better than Sting"],
      [1, "Weaponized Bubonic Plague", "Either that, or a can of pudding. Actually, it says pudding on the side. Oh well, still good for scumming"],
      [1, "Name of Dread Pirate Roberts", "It's Dread Pirate Roberts"],
      [1, "BFG", "Wow, that's a big FG"],
      [1, "Y2K Bug", "Eternally annoying"],
      [2, "Dolly the Clone", "Baaaa Baaaa"],
      [1, "Sand Dune", "Worm included"],
      [2, "All Your Base", "They are still with Us"],
      [2, "Kenny's Corpse", "Likely to come back, sooner or later"],
      [2, "Captain America's Shield", "It really doesn't have a better name"],
      [1, "Sword in the Stone", "Still stuck in the rock, but maybe you can throw the rock at somebody"],
      [2, "H2O", "Slippery when wet"],
      [4, "Higgs Boson", "God, what a particle"],
      [3, "Mobius Strip", "Endless source of entertainment"],
      [4, "Schrodinger's Cat", "Feeling lucky, punk?"],
      [1, "Occam's Razor", "Simplest incarnation would be a knife"],
      [2, "Guy Fawkes Mask", "Remember November, then September and December"],
      [1, "Sharks", "With freaking lasers on their heads"],
      [4, "Charles Darwin", "He takes all the credit"],
      [4, "Grandfather Clock", "It just looks like my grandfather's clock"],
      [3, "Tablet PC", "As obsolete as sliced bread"],
      [3, "Disc Brakes", "On their way to becoming disco brakes"],
      [3, "Jar of Natural Peanut Butter"],
      [4, "Satellite Dish", "FOX News never, ever included"],
      [1, "Terminator Pinball Machine", "Hasta la parachoques, baby!"],
      [1, "Ski Pole", "Sorry dude, wish it was a snowboard"],
      [4, "Abacus", "Primitive, but maybe you won't break it right away"],
      [1, "Plastic Spork", "Because there is no spoon"],
      [2, "Sunglasses", "Best worn at night"],
      [4, "Compass", "Handy for those planets with dynamo!"],
      [4, "Magic 8 Ball", "Outlook is hazy"],
      [3, "Roller Skates", "Now you can work at the fly-in"],
      [2, "Garlic", "What do you call a duck with fangs?"],
      [3, "Air Conditioner", "no exquisite sin greater... than central air"],
      [2, "St. John's Wort", "Whoops, thought it was a mole"],
      [3, "Bubble Gum", "And you were all outta gum"],
      [4, "Planet-arium", "Thinks it just looks good"],
      [1, "Ping Pong Ball", "Provides a discount on drinks"],
      [4, "Bits", "The Stuffed Animal Parrot. Also a pirate"],
      [2, "Carton of Cigarettes", "Worth more in prison"],
      [3, "8-Track Tape Player", "Now if only you had tapes..."],
      [3, "Commodore 64", "640K ought to be enough for anybody, but 64 was even better"],
      [2, "Fiberglass dome", "What was it made of before?"],
      [1, "ET Video Game", "For Atari 2600, and We have plenty"],
      [2, "Retaining Wall Block", "Manufactured Concrete"],
      [3, "Can of Baked Beans", "Anyone have a can opener?"],
      [3, "Donuts, Baker's Dozen", "A long lost art"],
      [1, "Reaper", "Don't fear the reaper"],
      [4, "Eiffel Tower Souveneir", "Cheap plastic imitation"],
      [4, "Bifocals", "Well aged"],
      [4, "Expired Nuclear Missile", "Now a glowstick"],
      [2, "New Year's Hat 1988", "It was a good year"],
      [1, "Lightwaver", "We said waver, and it's better than the original"],
      [3, "Hot Rod", "Best not to wonder what makes it hot"],
      [3, "Dimension Jump", "Like for Quinn Mallory, it's a 1-way trip. But luckly you know the way back"],
      [4, "Moodstone", "Could be broken, it's always showing red"],
      [2, "Tragically Unfashionable Clothes", "A few more years, and they'll come back in style"],
      [4, "Photon", "No torpedo. Maybe you should put it in a torpedo"],
      [4, "Censor", "Get another for better sensors"],
      [3, "Big Mick", "The Giant Chedder Burger"],
      [3, "Warp Drive", "Arrgh, the laws of science be a harsh mistress"],
      [1, "Ulfberht Sword", "Fused with materia"],
      [4, "Hourglass", "Or maybe the Sands of Time, but probably not"],
      [2, "Superman's Cape", "Solar powered"],
      [2, "Ankh", "Cheap Plastic Imitation"],
      [4, "Sunstone", "Sunny-side up"],
      [3, "Warped Core", "Needs a core dump"],
      [1, "Pandora's Box", "There's a party inside and everyone's invited"],
      [1, "The Freak", "aka Zombie Dance Party"],
      [2, "Spacesuit", "Skin-tight leather edition"],
      [3, "Cruel Grue Gruel", "A step up from grits"],
      [3, "Gravitron", "Or maybe you just put on weight"],
      [2, "The Precious", "You won't be thinking that in the morning"],
      [2, "Hockey Mask", "Ready to use, just add psychopath"],
      [2, "Parachute Pants", "You can't touch these"],
      [3, "Ice.", "Ice, baby. Too dry."],
      [2, "Dead Man's Chest", "He wasn't dead when you found him"],
      [2, "Davy Jones' Locker", "Wouldn't it float?"],
      [3, "Recuperation Lounge", "We keep telling you..."],
      [2, "Plague Doctor Mask", "Breeds plague, but still smells good"],
      [3, "Death Cart", "Bring out your dead!"],
      [1, "King of the World", "It's good to be the king"],
      [3, "2400 Baud Modem", "Time to trade in your old 1200"],
      [2, "Bullet Time", "Whoa."],
      [1, "Flower Power Buff", "Do you eat it, or what?"],
      [2, "1UP Mushroom", "Either that, or deathcap"],
      [4, "Pinky and the Brain", "Joining you on a common mission"],
      [1, "Silver-Coated Magnum", "Silver for the professional headshot"],
      [1, "AWP", "Earplugs included"],
      [1, "It's a Trap", "Just like marriage, and Texas"],
      [4, "Maths", "Use them wisely"],
      [4, "Quantum Computer", "Turns out it only knows 0s and 1s"],
      [3, "Large Hadron Collider", "My, those are some huge bosons"],
      [3, "Origami Crane", "More like a mocking bird with that stare"],
      [2, "Petrified Wood", "Heh, heh"],
      [1, "Black Pudding", "Is there ever a bad time for pudding?"],
      [4, "Newton's Telescope", "I can see Russia from here"],
      [4, "Seismograph", "Looks a bit shaky"],
      [4, "Raleigh Scattering", "Why is your sky blue?"],
      [1, "Bowling Pin", "Well on your way to a dull Saturday afternoon"],
      [2, "Parachute", "You hope"],
      [3, "Diving Bell", "And it's powered by steam, punk"],
      [4, "Sextant", "Arr, efficient navigation with a side of blindness"],
      [2, "Gas Mask", "Thee who smelt it, dealt it"],
      [3, "Comic Book", "First digital edition, sans cover"],
      [3, "Can of Soft Drink", "Shaken, not stirred"],
      [2, "Recycle Bin", "Same as the trash can, but more colorful"],
      [3, "Artificial Heart", "Good for artifical relationships"],
      [3, "Autopilot", "Well actually it's you, but same difference to Us"],
      [1, "Electric Guitar", "Notice: no Stairway"],
      [4, "Black Light", "Tooth whitener for the poor alien in your corner of the galaxy"],
      [4, "Lava Lamp", "We thought plain lava was too obvious"],
      [4, "Bulletin Board System", "Barren Realms Elite, anyone?"],
      [3, "Candy Corn", "The original biofuel"],
      [4, "GPS Satellite", "Now space debris"],
      [3, "6-Pack Cooler", "Filled with A&W Root Beer"],
      [3, "Cotton Candy", "Actually just cotton, We mistook you for a goat"],
      [2, "Crash Test Dummy", "Once, there was a kid who... flew into a singularity and..."],
      [4, "Credit Card", "Only good for cameras and Hawaiian shirts"],
      [2, "Defibrilator", "A shocking find"],
      [1, "Dental Floss", "Huh, made of super tensile steel"],
      [4, "Full Body Scanner", "Must be broken, nothing in the head but cheese wiz"],
      [3, "Garage Door Opener", "Might be nice to have a garage door closer as well, but doesn't really matter until you find a garage door. And a garage"],
      [3, "General Tso's Chicken", "i.e., \"General Tso\"'s \"Chicken\""],
      [1, "Hammond Organ", "Press ALT-F4 to hear some Reggie Wilson"],
      [2, "Holographic Projection System", "Help Us Obi-Wan, they stole our projection system"],
      [3, "Root Beer Float", "Frosty, foamy, and full of fungus"],
      [2, "Jukebox", "Ehhhhh..."],
      [2, "Lightning Rod", "Exactly the same as a rod"],
      [2, "Bellybutton Lint", "Always fuzzy, always purple"],
      [2, "Monopoly Hat", "Nope, just a small upside-down bucket"],
      [3, "Monster Truck Wheels", "Perfect size for Our micro machines"],
      [1, "Napalm", "2.13 parts gasoline, 2.13 parts styrofoam"],
      [3, "Segway", "A quicker way of saying \"bankrupt\""],
      [3, "Skateboard", "Rocket-powered, square and rotating. May not actually fit the definition of a skateboard, but We're marketing it to the kids"],
      [3, "Skee Ball", "Or as We like to call it, whee ball"],
      [2, "Smoke Detector", "Detects smoke in the future, too. You're future doesn't look good"],
      [3, "Snowboard", "Yeah dude don't even worry 'bout the snow bra!"],
      [3, "Solar Array", "Requires sunglasses at night"],
      [1, "Taser", "Less-lethal weaponry"],
      [2, "Used Tea Bag", "Our favorite. They're like crack to Us"],
      [4, "Kaleidoscope", "Retro. Colorful. Lethal. Yes, this will be perfect"],
      [3, "Teleprompter", "Just move your head a lot and no one will notice"],
      [3, "Oil Drilling Rig", "Oil spill cleanup kit included"],
      [4, "Traffic Cone", "Maybe space isn't that deep after all"],
      [2, "Obsidian Statue", "Thanks for taking this one off Our hands"],
      [2, "Tupperware Set", "Bulletproof, and at these prices!"],
      [3, "TV Dinner", "97% salt"],
      [4, "Uno Wild Draw 2", "Skip red. Skip blue"],
      [1, "Superglue", "Physics demands it lands on your fingers"],
      [2, "Air Bag", "Just like your head"],
      [2, "Tinfoil Hat", "Do you really want Us to explain this one to you?"],
      [4, "Atomic Clock", "Our smallest edition yet"],
      [3, "Pilot V-Ball Pen", "Extra fine!"],
      [2, "Acetaminophen", "aka masking the root cause"],
      [2, "Aloe Vera", "Mildly poisous, not at all helpful, but you keep buying it"],
      [2, "Bulletproof Vest", "Careful, those who go looking for fights get them"],
      [1, "Ethernet Cable", "Choice of yellow, tangled and obsolete. And they're all the same"],
      [1, "Steinbrenner's Bat", "Twice broken"],
      [1, "Boomerang", "And now you're cooler than Us?"],
      [3, "Printing Press", "Read this literature and it will change your life"],
      [1, "Bunsen Burner", "Poor, gullible Bunsen"],
      [4, "Recycled Paper", "2% Post-consumer content"],
      [3, "Astral Plane", "A Boeing 727"],
      [3, "Yougart", "With Strawberries"],
      [3, "Cells", "Cells are bad. My uncle lives in a cell."],
      [4, "Message in a bottle", "Just has a bunch of profanity"],
      [1, "$100 bill", "This note is legal tender for all debts, public and private. Except in space."],
      [2, "Puncture Repair Kit", "Always on standby"],
      [4, "Occular Halo", "Monocles are making a comeback"],
      [1, "Hard Fruit Punch", "That's how Houdini died"],
      [1, "Gorignak", "Really just a rock, how bad can it be"],
      [1, "Pig Lizard", "Less threatening than a rock"],
      [3, "Bouyant Carrack", "It's only a model"],
      [1, "Famous bobblehead", "Can't remember who it is"],
      [1, "Half-carrot", "And half something else, but you're not sure what"],
      [3, "TARDIS", "The awesome rover drifting in space"],
      [4, "Lost Tapes", "Now if only you had a betamax"],
      [2, "Jelly Baby", "Useful for keeping people away"],
      [1, "Fallen Star", "Just a lump of rock"],
      [3, "Space dust", "Or is it star dust?"],
      [4, "Space flies", "Glow bugs in space, good for nostalgia"],
      [3, "Xenon's Driver", "Always a getaway in the nick of time"],
      [3, "Black Pearl", "Looks scarier than it really is"],
      [4, "Universe on a Belt", "too small to fit a neck, maybe you can use it as a wristguard"],
      [2, "Cloning Vat", "odd, you didn't expect to see just one"],
      [4, "RNG Vision Goggles", "They don't change the outcome, but at least you can see it coming. So in effect, they do nothing"],
      [3, "1-Week Pass to Riza", "Now if you only knew how to find it"],
      [4, "Paper Books", "certainly not going to read them, maybe can use them to prop up the console"],
      [4, "e-Books", "even less useful than paper books"],
      [3, "Klein Bottle", "thoroughly twisted"],
      [1, "Matrix Sequels", "You wish you only knew kung-fu"],
      [2, "Carbonite", "too cold, too cold"],
      [3, "Telephone Booth", "Works better with bubblegum, but really only good for making history"],
      [2, "20 Bear Pelts", "An oddly even number to find by accident"],
      [1, "Invisible Stalker", "Flattering to have a stalker, even one you can't see"],
      [2, "Golden Fleece", "Still itchy, even made out of gold"],
      [4, "100-sided die", "Hardcore, but could use a harder core. It keeps rolling off the table"],
      [4, "Coin", "Good to flip for those tough decisions"],
      [4, "Night Light", "It's dark out there"],
      [1, "Annihilatrix", "Best sold for scrap"],
      [1, "Boom Boom", "It's just a euphemism"],
      [2, "Green Backpack", "Mathematical!"],
      [4, "Worthless Beads", "But they must be worth something to somebody"],
      [2, "Horn of Africa", "Probably from an ancient, extinct spacefaring hippo species"],
      [4, "Megaphone", "Now they can hear you scream"],
      [4, "Humpback Whale Recording", "Never know when it will come in handy"],
      [4, "Gygax's 20-sided Die", "For all to cherish and share"],
      [2, "Absolute Zero", "What other people think of you"],
      [1, "Chuck Norris's Leg", "Simply amazing, and you haven't even used it yet"],
      [1, "Single Atom Sword", "It dices, it slices... just don't turn it sideways and forget where it is"],
      [3, "Levitating Pool Table", "it's made out of water, too!"],
      [4, "Looking Glass", "The only way to go through one"],
      [3, "The Cube", "We know not where it comes from, but it's pretty obvious what it looks like"],
      [3, "The Cone", "Before time began, there was The Cone. And the Cylinder. And some other stuff."],
      [1, "Allspark", "These often show up after rubbing your feet on the carpet"],
      [3, "Lead Zepplin", "It might actually float, if you weren't in the vacuum of space"],
      [3, "Tenori-on", "Great for those long journeys"],
      [4, "Five-and-a-quarter Inch Floppy", "Not just old... so old they used Imperial units"],
      [4, "Box", "What's in the box? It's not very heavy"],
      [4, "Empty Certificate Frame", "Could be useful for posting some sort of achievement"],
      [2, "Sassafras Workbench", "Good for all kinds of things"],
      [1, "The Bomb", "Maybe you should set us up"],
      [2, "Honey Badger Tail", "Someone took its tail, and it just didn't care"],
      [4, "Tnetennba", "Wow, that's a nice tnetennba"],
      [2, "UV-shielded Sunglasses", "For staring at the sun"],
      [3, "AX-5 Hard-Shell Space Suit", "Retro inclined"],
      [2, "Exotic Matter", "More believable than irreconcilable differences"],
      [3, "Time Machine", "Only Goes Forward… Just Watch out for Sewer Dwellers and Giant Crabs"],
      [4, "Universal Translator", "A bit redundant, since everyone speaks english already"],
      [1, "Quantum Suicide Booth", "Its meaning depends on how you look at it"],
      [1, "Shrink Ray", "Honey, you better see this"],
      [3, "Holodeck", "Our last invention, ever"],
      [2, "Mame Cabinet", "For those long journeys"],
      [4, "Dark Scanner", "Best not to look into it"],
      [3, "Digital Rotoscope", "Could be useful for speeding things up"],
      [4, "Career Chip", "With a small hologram that says 'Space Adventurer (Delivery Boy)'"],
      [2, "Dr. FlimFlam's Miracle Cream", "Use responsibly"],
      [1, "Lucy Liubot", "Still programmed to be violent"],
      [2, "Cryotube with Preset Timer", "Best not to lean in chairs"],
      [1, "Hypnotoad on TV", "Thank you, Hypnotoad, for being so very very awesome at everything"],
      [3, "Flying Train", "Only accelerates up to 87 mph"],
      [4, "D&D Monsters Manual", "2nd Edition"],
      [2, "A Ring", "Not The Ring, or even One of The Rings, but still a ring"],
      [4, "Pillowpants Detection Device", "An obvious evolution on parachute pants"],
      [3, "Earl Grey", "Hot. Very, very hot"],
      [1, "Metal Pipe", "For a frantic dream, or maybe to be a plumber"],
      [4, "Broken Stalin Statue", "Even in space totalitarianism failed"],
      [2, "Raven Locks", "You'd rather rave with suede, but these should do fine"],
      [2, "Radiation Shield", "A meter of material known by the state of California to cause cancer"],
      [3, "Bottle of Martian H2O", "Unremarkable water really, except of course that it came from Mars"],
      [4, "Fool's Gold", "Trust Us and ignore the name, it's the real thing"],
      [3, "Super Bouncy Ball", "Hard to believe, but it really is super"],
      [2, "Skeletor's Purple Hood", "Timeless Stylin'"],
      [2, "Trenchcoat", "Also great for swimming"],
      [3, "Spice Melange", "Closely guarded secret: it can also be made from oranges, carrots, and Dennis Rodman"],
      [3, "Forced Evolutionary Virus", "Everyone who goes in comes out looking like Pamela Anderson"],
      [1, "Heaven's Will", "You feel taller just holding it"],
      [1, "Lawgiver", "Trust Us, it's best used as a paperweight"],
      [2, "Robotic Left Arm", "It's a shame you're rather attached to your current one. But We can fix that for you"],
      [4, "Night-Vision Sunglasses", "For those too cool to take them off"],
      [3, "Rotor Volocopter", "Looks as cool as it sounds"],
      [2, "Water Purifier", "Now if only you knew how to find dirty water"],
      [1, "Brick", "More useful than it seems"],
      [3, "Antigravity Boots", "Whoever invented this one just didn't have their feet on the ground"],
      [2, "Large Plastic Ball", "Nobody expects the Spanish quarantine"],
      [4, "BioCola", "Once again, it's people"],
      [2, "Snow Shovel", "If you're gunna live in snow, best to learn to love it"],
      [4, "Robotic companion", "Companion, not escort"],
      [1, "Steampunk Steamiron", "Just a matter of time"],
      [3, "Pop Tart", "Still the breakfast of spacefaring champions"],
      [2, "Surgical Mask", "Just thinking ahead"],
      [4, "Bar Pin", "Never too late to change careers"],
      [3, "Fusion in a Bottle", "Only mildly warm"],
      [4, "Black Lotus", "Very poor condition, probably fake"],
      [2, "Sol Ring", "It's got the power of a star... shame it wasn't a big star"],
      [4, "Ocular Implants", "Time to ditch the visor"],
      [1, "Swiss Army Knife", "106 functions and you still can't find your ship keys"],
      [2, "Sunscreen", "You'll need SPF 10,000 where you're heading"],
      [3, "Orbnauticus", "He feels pretty... oh, so pretty"],
      [2, "Omega 14", "Lets you go back in time, just far enough to hit the restroom"],
      [1, "General Chaos", "Major Pain and Coronel Sanders made that man a gunner. He's their cousin"],
      [1, "Spoon of Destiny", "It hath power over all things"],
      [2, "Silver Spoon", "There is no Silver Spoon"],
      [4, "Destiny of Destiny", "Now with Inception power"],
      [2, "Space Heater", "Another common misconception is that space is hot. It's not. It's not cold either. Apparently... and now We have a surplus of heaters"],
      [1, "Quad Glacier", "Move a little to the left... to the left... more. MORE We said. Oh, We meant right. Well, just forget it now."],
      [1, "Wirt's Leg", "The gift that just keeps on giving"],
      [2, "Red Stapler", "The stories this stapler could tell... if it weren't a stapler"],
      [3, "Timbit", "Just one"],
      [2, "Time Dilation Containment Chamber", "Rather self-explanatory"],
      [2, "Tractor Beam", "Easily disrupted, highly unreliable... basically you're better off with a lasso and a miniature horse"],
      [2, "Repulsar Beam", "From the smell of things, you've activated this one already"],
      [1, "Extremely Depressed Personal Robot", "And he says he doesn't like you very much"],
      [1, "Robot-Android-Cyborg-Replicant-Simulant Hybrid", "And it should have been part therapist, considering the multiple personaities"],
      [4, "Telepathy Bauble", "Also known as a cell phone"],
      [2, "Alternate History Reactor", "And every one generated seems to have to an invulnerable, immortal Marilyn Monroe"],
      [2, "Anti-aging Cream", "We picked this one out especially for you"],
      [1, "The Voice", "And We're pretty sure it commands you to bring Us more black pudding"],
      [2, "Invisibility Cloak", "We'd be happy to deliver it, but forgot where We put it"],
      [1, "Photon Torpedo", "This one won't detonate until someone forces a quantum interaction. So We'd suggest no sudden movement"],
      [3, "WD-40", "Like Head & Shoulders: if you use enough of it, you'll probably need to use a lot more of it"],
      [1, "Cabbage Patch Kid", "What happens in Vegas between Pinocchio and lettuce didn't stay in Vegas"],
      [4, "Scientific Calculator", "An elf with an abacus"],
      [4, "CAT-Scan Machine", "Warning: may affect pacemakers and UFO radiation shields"],
      [1, "Chain Saw", "Still the weapon of choice"],
      [2, "Chapstick", "Spreadable and edible"],
      [3, "Canned Cheese", "Humans were given the resources of a primary system, and this is what you came up with?"],
      [3, "Chocolate Easter Bunny", "It's gigantic... oh, and armed with a minigun"],
      [1, "Dragon Cigarette Lighter", "Filled with cool mini-dice that light up when you need a smoke"],
      [4, "Baritone Saxophone", "100% brass, 0% brass band"],
      [2, "Hearing Aids", "We're giving you aids"],
      [4, "Contact Lens", "20/20 is only good in hindsight"],
      [4, "Cotton Swabs", "Warning: may puncture eardurms. Note: not good for anything else"],
      [3, "Cruise Control", "Easily mistaken for autopilot, but only once"],
      [1, "Depth Charge", "At the rate your ship burns energy, you'll need a charge this big"],
      [2, "Dialysis Machine", "Just Our sense of humor"],
      [1, "Dry Ice", "Neither ice nor dry"],
      [1, "Stick of Dynamite", "Oh come on, it's more like a firecracker to Us"],
      [2, "Earmuffs", "Always trendy in a galaxy far, far away... where you should be"],
      [2, "Ear Plugs", "Don't worry, you'll still be able to hear Us"],
      [1, "Electric Chair", "We've been wanting to give you the Electric Chair"],
      [4, "Electron Macroscope", "Use your eyes, buddy"],
      [3, "Escalator", "Elevator going up, but it's still hard to lift"],
      [1, "Nigerian Spam", "Hang on... I'm about to be rich"],
      [2, "Exoskeleton", "Every skeleton's skeleton and now yours, too"],
      [3, "Holographic Doctor", "And opera singer"],
      [1, "Relativistic Bomb", "And relatively hostile"],
      [1, "Quad Laser", "Based on futuristic moon technology"],
      [2, "Aqueduct", "Romanes eunt domus"],
      [1, "Robot Santa Claus", "Uncle of the robot devil, and twice as nice"],
      [3, "Parallel Universe Box", "Either transports to an identical parallel universe, or it's just a box"],
      [1, "Doomsday Device", "The countdown is always stuck at 5 minutes before doom"],
      [1, "WMD", "Actually just a Texas politician with too many donors"],
      [2, "Reanimator", "Sure We can make it move again, but it can only dance The Freak"],
      [3, "Sparklematic 5200", "Junk in, shiny junk out"],
      [3, "Flying Car", "Ready for pickup in about five years"],
      [1, "Death Star Laser", "It's more like a death moon with a flashlight... We blame the marketing department"],
      [4, "Tarot Cards", "We have some bad news for you"],
		  [1, "The Power Nine", "Conveniently stored in the Library of Alexandria"],  // Magic: The Gathering.
      [1, "Insolent Crabs", "Not Alaskan King but We have it on good authority that they're huge"],  // Aqua Teen Hunger Force.
      [2, "Ogre Pinata", "With a matching donkey pinata that nobody wants"],  // Shrek.
      [3, "Spectral Mount", "Indefinitely chasing its own tail"],  // Wow.
      [2, "World Enlarger", "Gnomish technology, obviously"],  // WoW.
      [1, "Rocket Chicken", "Our bad on this one"],  // Adult Swim.
      [4, "Robot Chicken", "A highly intelligent device where We stored the Enterprise computer's memory"],  // Adult Swim.
      [1, "Rainbow Machine", "We told you we're not leprechauns"],  // Aqua Teen Hunger Force.
      [4, "Gem of True Sight", "A truly outrageous sighting"],  // DOTA.
      [1, "Eye of Skadi", "Pales in comparison to the Eye Patch of Skadi"],  // DOTA.
      [1, "Buriza", "The kitchen knife that never needs sharpening, and We'll throw in a ShamWOW"],  // DOTA.
      [3, "Pumped Up Kicks", "Put them on... and We'll be right back"],
      [2, "Linken's Sphere", "Did you say Abe Lincoln?"],
      [1, "Helm of the Dominator", "His real name is Jeff"],
      [1, "Monkey King Bar", "Galaxy-renouned cocktails"],
      [2, "Aegis of the Immortal", "Really makes Us wonder how We looted it"],
      [3, "Speed Skates", "Well, the ship is too big for walking"],
      [2, "Rune of Invisibility", "Still hard to read"],
      [2, "Aegis of the Legion", "A seriously oversized shield"],
      [1, "Guinsoo's Rageblade", "Ragers gotta rage"],
      [2, "Negatron Cloak", "All wrapped up in a graviton plexis"],
      [1, "Trinity Force", "Like waking up in bed with two models"],
      [2, "Blue Pill", "No, the other blue pill"],
      [4, "Red Pill", "Why oh why didn't you take the BLUE pill?"],
      [1, "Rootkit", "Made by Monsanto Corporation"],
      [4, "Jailbroken Smartphone", "Saved with a Get Out of Jail Free"],
      [3, "Stirmaster", "For two weeks We stirred and it made our coffee look like tea"],
      [4, "Steampunk Goggles", "They do nothing"],
      [1, "Xena's Chakram", "Aka Guinsoo's Rageblade"],
      [1, "Gabrielle's Quarterstaff", "Double-ended for pleasure"],
      [1, "Sword of Shanarra", "You can't handle the truth"],
      [1, "Iocane Powder", "This should help you embark on a land war in Asia"],
      [1, "Despair Squid Venom", "A blatant giveaway"],
      [3, "Tiberium", "Known to form from old gym socks"],
      [1, "Mako", "Highly reactive, and known to spawn large factories"],
      [1, "Stormbringer", "Don't be surprised if it murders your dog"],
      [1, "Dagger of Time", "Serrated and wrinkle-shaped"],
      [1, "General Order 24", "Just wait until you see General Order 25"],
      [1, "Krenim Incursion", "At most 99.8% accurate, not that you'll care"],
      [1, "Mega Maid", "Have a nice day"],
      [1, "BFG 9000", "The prior 8999 models are stored in Our BF Warehouse"],
      [1, "Red Curry", "We were elected to lead, not to feed"],
      [1, "Gatling Gun", "More than adequate for your soft tissue"],
      [2, "Geodesic Dome", "We have Buckeyballs of steel"],
      [2, "Ghost Buster Trap", "Don't look at it, it's too retro"],
      [1, "Fly Swatter", "You may as well take it, apparently We need a bigger one"],  // To swat the player.
      [4, "Glow in the Dark Pencil", "How else would you write in the dark?"],
      [1, "Grenade", "From Antioch, made by priests and filled with moley"],
      [1, "Guillotine", "The French made good executives"],
      [1, "Halloween Pumpkin", "Reminds Us of a better time"],
      [3, "Toy Helicopter", "Or an Apache, depends on who's piloting"],
      [2, "Horseshoe", "A perfect fit, from the looks of it"],
      [2, "Rabbit Foot", "His name was Fluffykins"],
      [3, "Remote Ignition System", "Our way of saying We put a bomb on your ship"],
      [3, "Instant Mashed Poatoes", "Does not obey the laws of physics"],
      [3, "Hot Coffee", "Perilous to you, not to Us"],
      [4, "Lie Detector", "This one's been broken since you arrived"],
      [2, "Superhero Lunchbox"],
      [3, "Bag of Tiny Marshmallows", "We felt this a more fitting reqard"],
      [4, "Halogen Lamp", "A chance to explode your ship from the inside, yet functional"],
      [2, "Flintstone's Vitamin", "Some might call them a vitamin freak"],
      [1, "RNG Voodoo Doll", "Made especially for you"],
      [1, "Lag of Death", "We think... We heard secondhand"],
      [4, "Mail-Order Bride", "Figued We'd just cut out the middle-man. Heh"],
      [1, "Windows Me", "Fogged-over and still broken"],
      [1, "Paintball Gun", "Beter to use all your ammo, the disposal costs are obscene"],
      [4, "Rain Gauge", "Always empty, yet often struck by lightning"],
      [3, "Half-moon cookie", "We'll give you a full moon brownie, too"],
      [4, "MP3 Player", "Pre-loaded with Spears and Timberlake"],
      [4, "Neon 'Open' Sign", "Figuratively... don't come back"],
      [4, "Fiery Red Odomoter", "To match your fiery red pitchfork and fiery red tail"],
      [4, "Water Divining Rod", "67% accurate"],
      [3, "Pacemaker", "Maybe you should pick it up"],
      [2, "Prosthetic Leg", "You'll need this when Bruno shows up"],
      [3, "Bog Robot", "Does the laundry, too"],
      [3, "Rollerblades", "Great way to travel around a really big ship"],
      [3, "Root Beer", "Best choice on planets stuck in 1923"],
      [2, "Seat Belt", "34% compliance last month, 35% next month"],
      [4, "Silly Putty", "It can read newspapers, too"],
      [3, "Sliced Bread", "The best thing since time travel"],
      [4, "Slide Rule", "You, dark times... almost as bad as the fascists"],
      [3, "Tennis Shoes", "White, and now stuffed"],
      [4, "Sonar", "Now you're Batman... or bat-boy"],
      [3, "Spark Plugs", "We'd call you Frankenstien, but you're a monster"],
      [4, "Rave Glowstick", "Like suede"],
      [1, "White-out", "We'd prefer to erase you from history altogether"],
      [1, "Pointy Stick", "Special edition, even"],
      [1, "Foam Nunchucks", "Ancient weapon of foam ninjas"],
      [1, "Upgraded Raptors", "Entirely unnecessary, but their overwhelming power makes Us laugh"],
      [1, "Orbital Weapon Platform", "And now orbiting your ship"],
      [4, "20-sided die", "Time to reroll, there are 19 more ways to die"],
      [3, "Quantum Tube Ship", "Built by leptons, made for quarks"],
      [3, "Fused Gummy Bears", "That's the risk of bouncing too hard"],
      [4, "Glow in the Dark Stars", "Fooled you... every star glows in the dark"],
      [3, "Platform Shoes", "Now you can see out your cockpit"],
      [2, "Bell Bottoms", "Almost like going commando"],
      [1, "The Blob", "Basically silly putty or a beautiful katamari"],
      [2, "Woolly Socks", "Packed with itch, but man do they breathe"],
      [4, "Monster Mash Meter", "Stuck at 0%"],
      [1, "Battering Ram", "And yet We have yet to lock the door"],
      [1, "Sniper Rifle", "Double points for hat tricks"],
      [1, "Shotgun", "Guess you called it"],
      [1, "Missile Launcher", "We take you for an RPG fan"],
      [1, "Rail Gun", "Outdated, inefficient, and totally awesome"],
      [1, "Flamethrower", "Good choices if you meet some flammable aliens"],
      [2, "Static Shield", "Best mosquito defence We have available"],
      [4, "Autotarget System", "Kindly preprogrammed with a taste for flesh"],
      [1, "Starcannon", "Not literally, it's just a circus prop"],
      [1, "Harpoon", "You'll need this for those frequent moon visits"],
      [4, "Jammed Radar", "There's something on it"],
      [1, "Bow and Arrow", "A broken arrow, now bow"],
      [2, "A Good Thing", "Trust Us, it's a good thing"],
      [1, "Orbital Strike", "Silent but deadly"],
      [1, "Pick Axe", "Made of solid gold, yet it still breaks rocks"],
      [4, "Shard of Starlight"],
      [2, "Starwalt Band", "They ran"],
      [2, "Free Life", "Free as in soon to be liberated"],
      [3, "Offworld Outsourcing", "Offworld replicating is allowed there too"],
      [1, "Logic Bomb", "Carries a maximum sentence of 10 years and 250k"],
      [3, "Infinite Loop", "An nth-complexity, infinite, binary loop, to be precise"],
      [3, "Replicator", "Replicate her? You hardly know her!"],
      [4, "Character Sheet", "The game is in learning to play"],
      [1, "Destiny Wand", "And it doesn't look bright"],
      [4, "Binoculars", "The most alert of the theropods"],
      [2, "Exosuit", "For spacefaring insects"],
      [4, "Babelfish", "Little, yellow and tastey"],
      [2, "Penny Jar", "A penny saved depreciates with inflation post-1972"],
      [2, "Amulet of Life Saving", "We stole it from a dead guy"],
      [4, "Stardust", "And it keeps getting everywhere"],
      [1, "Boom stick", "This one was Ours"],
      [4, "Tricorder", "Because you only ever need to know three things"],
      [4, "Metal Detector", "Mostly finds tinfoil hats"],
      [3, "Thermocouple", "The best way to couple"],
      [4, "Spider Sense", "It's telling you to leave"],
      [3, "Pink Fluffy Dice", "To match your tastes"],
      [2, "Air Freshener", "Take it with a hint"],
      [4, "Shoes on a Powerline", "Happy birthday to you!"],
      [1, "Greek Fire", "Invented by Prometheus, delivered by Icarus"],
      [1, "Voodoo Doll", "It looks just like you"],
      [4, "+5 Hat of Sexderity", "And you still won't get lucky"],
      [2, "Minor Ascension Kit", "It's only a model"],
      [1, "Ascension Kit", "Better take your camera"],
      [3, "Major Ascension Kit", "Stuffed full of K rations"],
      [4, "Elite Ascension Kit", "Just a shiny necklace"],
      [3, "Slider's Gizmo", "We're hoping it works as well for you as for Jerry O'Connell"],
      [3, "Energy Shake", "To shake, or not to shake"],
      [2, "Magical Cloak of Fabulousness", "Speaks for itself, and it won't shup up"],
      [4, "Plastic Flowers", "We prefer the term undead"],
      [2, "Diamond Ring", "Probably cursed"],
      [4, "Starscanner", "Just use your eyes, buddy"],
      [4, "Gold Pan", "Precursor to the gold pandemic"],
      [2, "Chameleon Suit", "Usually turns you into an anthropomorphic squirrel"],
      [2, "Mighty Morphing Suit", "Should turn you into Chuck Norris, but doesn't"],
      [2, "Touch o' Lag", "Just enough to do the trick"],
      [3, "Beryllium Sphere","Sold by beryl children"],
      [3, "Dilithium Ubermatrix","Also knows as the quadmonium mediarray"],
      [3, "Tesseract", "Yet it looks just like a misshapen cube"],
      [1, "Necronomnomnomicon","Heavy on the nom"],
      [1, "Chuck Norris Something","Could be his shoelace, or dandruff... doesn't really matter"],
      [2, "Fountain of Youth","We're hoping it returns you to your original state"],
      [2, "Smoke Shifter","Left-handed, and crusty"],
      [3, "Spirit Rover","Ironically named"],
      [3, "Opportunity Rover","Probably just wondering what happened to his cousin"],
      [3, "Curiosity Rover","Seeks out new life and new civilizations"],
      [4, "Multiverse Kaleidoscopic Viewer","Same boring world, in different colors"],
      [3, "Multipass","Good for all five elements"],
      [1, "Pwned","Made by an eight-year old, no less"],
      [2, "TMNT", "Another backronym"],
      [2, "Big Daddy","Relatively speaking"],
      [3, "Needlessly Small Rod","Don't worry, We hear it's more about how you use it"],
      [3, "Water Noodle","Sluuuuuuurp!"],
      [1, "Fast-twitch Muscle Fiber","Wrong for all the right reasons"],
      [4, "Eerie Tombstone","We took the liberty to engrave your name and a date"],
      [3, "Gangnam Style","98% Korean"],
      [4, "Astral Projection","And still ugly in all realms"],
      [3, "Tornado Bottle","Filled with sharks"],
      [2, "Unicorn Horn","This makes you feel great!"],
      [4, "Tabula Rasa","It means 'You Monster', in gibberish"],
      [1, "Master Blaster","We knew him before he got the aim"],
      [2, "Animal Paw","Maybe a rabbit foot or bear claw"],
      [2, "Police Box","Basically the same powers as a telephone booth"],
      [3, "Space Elevator","Elevator going up"],
      [3, "Astronaut Ice Cream","Always cosmicpolitan"],
      [3, "Math Coprocessor","Push the turbo button for added effect"],
      [1, "Heroic Sidekick","Wink wink, nudge nudge"],
      [3, "Rainbow Bridge","Created by space rain"],
      [3, "Holy Grail","You chose poorly"],
      [1, "Castle Anthrax","You looked like you could use a little peril"],
      [3, "Airship","All yours, Cid"],
      [3, "Genie","We recommend wishing for more wishes"],
      [3, "Wigwam","You're looking tense"],
      [4, "Gygax's Gyroplane","Gravitationally grounded"],
      [2, "Xagyg's Xanadu","Filled with colorful dodecahedrons"],
      [3, "Space Weevil","Its first bite will be in the eye"],
      [2, "Respec Knuckles","Better than the reroll rockets"],
      [4, "Canary in a Cage","The cage is empty"],
      [3, "Oragami Kit","We thought you should make some peace cranes"],
      [3, "Zepplin","Smoke 'em if you got 'em"],
      [3, "High-tech Zepplin","A chair and five thousand balloons"],
      [4, "Pilot's Light","Despite the NO SMOKING sign"],
      [3, "Buckyballs","i.e. extreme shrinkage"],
      [3, "Biodome","Built to hermetically seal Pauly Shore"],
      [2, "Nanotube","Used to build very small internets"],
      [2, "Cleftal Horizon","It's a technical term"],
      [3, "High-density Fuel Cells","Well-aged gas"],
      [4, "Biochip","Bet you can't eat just one"],
      [3, "Jet Pack","It seemed like a good idea at the time"],
      [3, "Space Activity Suit","For the moonwalk"],
      [4, "Parsec","Classier than a light year"],
      [3, "Solar Sail","Also known as St. Elmo's Starflare"],
      [3, "Nuclear Pulse Engine","Just repeats beep-beep-beep bop-bop-bop beep-beep-beep"],
      [3, "World Ship","We hope it takes you out of this world"],
      [1, "Plasma Rocket","It's on fire"],
      [2, "Piggy Bank"],
      [4, "Rose of the Winds"],
      [4, "Compass Rose"],
      [1, "Railgun"],
      [4, "Luck Dragon"],
      [1, "Lock, Stock and Barrel"],
      [1, "Ion Cannon"],
      [1, "Noisy Cricket"],
      [1, "Spear of Destiny"],
      [4, "Star Cross"],
      [1, "Borno's Blaster"],
      [1, "Sword of Ooo"],
      [2, "White Bear Hat"],
      [4, "Maltese Falcon"],
      [3, "Chunnel"],
      [4, "Gygax's Galaxies"],
      [1, "Cattle Prod"],
      [2, "Quantum Wire"],
      [3, "Incessant Obsolescence Postulate"],
      [3, "Ion Thruster"],
      [1, "Fission-fragment Rocket"],
      [3, "Interstellar Ramjet"],
      [3, "Magnetic Sail"],
      [3, "100 Year Starship"],
      [3, "Antigravity Kit"],
      [3, "Arcjet"],
      [2, "Light Barrier Shield"],
      [3, "Photon Propulsion Engine"],
      [3, "Pulse Detonation Engine"],
      [3, "Space Fountain"],
      [2, "Terraform Pod"],
      [4, "Universal Computer"],
      [4, "Hitchhiker's Guide", "Revised edition. On the front: PANIC!"],
      [4, "Computronium"],
      [3, "Ice Cream on a Light Cone"],
      [3, "Mindfood"],
      [3, "Neutronium"],
      [3, "Dusty Plasma Sail"],
      [2, "Transparent Aluminum"],
      [4, "Cool-Looking Visor"],
      [3, "Robotic Hand"],
      [2, "Robot Friend"],
      [2, "Cloaking Device"],
      [4, "Metaverse Compendium"],
      [1, "Ray Gun"],
      [2, "Bionic Nose"],
      [1, "Mind Control Sphere"],
      [4, "Virtual Reality"],
      [4, "Omega Ball-Point Pen"],
      [1, "Unexpected Neuse"],
      [1, "Crysknife"],
      [1, "Hunter-seeker"],
      [1, "Gundam Mobile Suit"],
      [1, "Metal Gear REX"],
      [1, "Neuralizer"],
      [1, "Pump-Action Shotgun"],
      [1, "Death Ray"],
      [1, "Disintegration Ray"],
      [1, "Katana"],
      [1, "Bat'leth"],
      [1, "D'k Tahg"],
      [2, "Force Field"],
      [2, "Maion Deflector Shield"],
      [2, "Sticky Hull Plating"],
      [2, "Ablative Armor"],
      [2, "Reactive Armor"],
      [1, "Kelen's Dagger"],
      [2, "Randuin's Omen"],
      [1, "Power Sword"],
      [1, "Havoc Staff"],
      [2, "Orko's Hat"],
      [2, "Delta-6 Accelerator Suit"],
      [1, "Amaranthine Gas"],
      [1, "Gom Jabbar"],
      [1, "Janis thorn"],
      [1, "Mosfungus"],
      [1, "Nightlock"],
      [1, "Poison Joke"],
      [1, "Red Water"],
      [1, "Strangler"],
      [1, "Ygramul's Poison"],
      [1, "FoxDie"],
      [1, "Batch 5"],
      [1, "Cardamine"],
      [1, "Chemical X"],
      [2, "G-23 Paxilon Hydrochlorate"],
      [1, "Kryptonite"],
      [1, "Phazon"],
      [1, "Terrazine"],
      [1, "Element Zero"],
      [2, "Latinum"],
      [3, "Morphite"],
      [2, "Stygium"],
      [3, "Thiotimoline"],
      [3, "Wonderflonium"],
      [1, "Quantium"],
      [1, "Hrunting"],
      [1, "Nægling"],
      [1, "XuanYuan's Sword"],
      [1, "Heavenly Sword"],
      [1, "Black Metal Sword"],
      [1, "Kusanagi-no-Tsurugi"],
      [1, "Chandrahasa"],
      [1, "Johnny Corkscrew"],
      [1, "Sword of Leah", "The truth is still out there..."],
      [1, "Vorpal Sword"],
      [1, "Callandor"],
      [1, "Rhindon"],
      [1, "Sword of Gryffindor"],
      [1, "Hadhafang"],
      [1, "Godsbane"],
      [1, "Green Destiny"],
      [1, "Mjölnir"],
      [1, "Grayswandir"],
      [1, "Mace of Cuthbert"],
      [1, "Frostmourne"],
      [1, "M41A Pulse Rifle"],
      [1, "M16 Mk. II Pulse Rifle"],
      [1, "Sword Kladenets"],
      [1, "Shamshir-e Zomorrodnegar"],
      [1, "Skofnung"],
      [1, "Sharur"],
      [1, "Ruyi Jingu Bang"],
      [1, "Dáinsleif"],
      [1, "Tyrfing"],
      [1, "Spear of Lugh"],
      [2, "Carnwennan"],
      [1, "Kusanagi"],
      [1, "Tizona"],
      [4, "Quantum Eigenstate Device"],
      [1, "Tauri Mark 9"],
      [3, "Tesla Coil"],
      [3, "Trampoline"],
      [2, "Umbrella"],
      [2, "Venetian Blinds"],
      [1, "Nomad"],
      [1, "Dr. Timicin's Photon"],
      [1, "31-79 JGb215"],
      [1, "Creatinator"],
      [1, "Hammerburst"],
      [1, "M1-L1 Triple-Pulse Rifle"],
      [1, "M392 DMR"],
      [1, "M72 Gauss Rifle"],
      [1, "Phased Plasma Rifle"],
      [3, "Pythagoras Device"],
      [1, "Raygun"],
      [1, "Chainsaw"],
      [1, "Fire Axe"],
      [1, "Dual .44 Magnums"],
      [1, "Dr. T's Lead Delivery System"],
      [1, "Pipe Bomb"],
      [1, "Phased Shockwave Generator"],
      [1, "Gamma Kyon Emitter"],
      [3, "Quicksilver"],
      [2, "Guy Falkes Mask", "Remember... remember September."],
      [4, "Disco Ball"],
      [3, "Tubular Bells"],
      [2, "Techmaturigical Repair Bots"],
      [4, "Googly Eyes"],
      [1, "Flaming Sledgehammer"],
      [4, "Heart Monitor Watch"],
      [1, "Cheese Slicer"],
      [3, "Treadmill Desk"],
      [2, "Bear Print Shoes"],
      [1, "Industrial Pollution"],
      [1, "Time Bomb"],
      [1, "Stink Bomb"],
      [1, "Bomb Shelter"],
      // intentional 0's
      [0, "Awesome Buff of Awesomeness", "Awesome!"],
      [0, "Boondoggle", "Needs some elbow grease and headlight fluid to be ready for the snipe hunt"],
      [0, "Continuum Transfunctioner", "Its mystery is exceeded only by its power"],
      [0, "TMNT Mutagen", "They say the secret is in the ooze, but it's actually just nitrate runoff"],
      [0, "Future Technology 1", "Our Future Technology 1 is incredibly advanced, obsoleted only by Future Technology 2. Oh..."],
      [0, "Magic Lamp", "Made in China for over 200 years"],
      [0, "Nanobots", "Mi minini mi mi mimimi mi mi"],
      [0, "Trinket of Awesomeness", "Better than sex"],
      [0, "Generic artifact", "Like you, it belongs in a museum"]
    ],			
		// The mountain-faced Engine module
    artiPrefixBase: function(seed, level) {
        return ST.randText(ST.artiAdv, seed + 323.13) + " " + ST.randText(ST.artiAdj, seed + 323.33);
    },
    artiPrefix: function(seed, level) {
			return "The "+this.artiPrefixBase(seed, level)+" ";
    },
    artiAdv: [
      "Abnormally",
      "Horribly",
      "Barely",
      "Blissfully",
		  "Astoundingly",
      "Completely",
      "Defiantly",
      "Exceedingly",
      "Fashionably",
			"Nearly",
			"Possibly",
      "Greatly",
      "Intently",
      "Loyally",
      "Likely",
      "Merrily",
      "Shyly",
      "Unfavorably",
      "Upward",
      "Utterly",
      "Wiggly",
      "Wisely",
      "Wrongly",
      "Virtually",
      "Vaguely",
      "Tepidly",
      "Terribly",
      "Quickly",
		  "Blatantly",
      "Quietly",
      "Politely",
      "Rarely",
      "Painfully",
      "Nimbly",
      "Partially",
      "Kindly",
      "Justly",
      "Jauntily",
      "Eternally",
      "Evenly",
      "Evidently",
      "Busily",
      "Briskly",
      "Calmly",
      "Loudly",
			"Hotly",
			"Massively",
      "Darkly",
      "Easily",
      "Almost",
      "Acutely",
      "Covertly",
      "Patiently",
      "Eagerly",
      "Carefully",
      "Securely",
      "Sometimes",
      "Usually",
      "Finally",
      "Just",
      "Boldly",
      "Doubtfully",
      "Irritably",
      "Madly",
      "Merrily",
      "Regularly",
      "Seldom",
      "Warmly",
      "Wildly",
			"Obviously",
			"Starkly",
      "Sternly",
      "Still",
      "Hardly",
      "Mostly",
      "Separately",
      "Always",
      "Closely",
      "Entirely",
      "Dismally",
      "Harshly",
      "Limply",
      "Much",
      "Funnily",
      "Firmly",
      "Truthfully",
      "Weirdly",
      "Expertly",
      "Sloppily",
      "Wickedly",
      "Now",
      "Lately",
      "Too",
      "Very",
      "Also",
      "Sufficiently",
      "Quite",
      "Diligently",
      "Equally",
      "Gently",
      "Greatly",
      "Foolishly",
      "Frankly",
      "Owlishly",
			"Randomly",
			"Procedurally",
      "Loftily",
      "Knottily",
      "Kookily",
      "Sadly",
			"Unflinchingly",
      "Shrilly",
      "Solemnly",
			"Grossly",
			"Cooly",
			"Openly",
			"Meekly",
      "Upright",
			"Occasionally",
			"Woefully",
      "Forever",
      "Viscously"
    ],
    artiAdj: [
      "Aged",
      "Unbalanced",
			"Stringy",
      "Bleak",
      "Cuddly",
      "Dense",
      "Elastic",
			"Deterministic",
      "Fatal",
      "Greedy",
			"Absurd",
			"Bland",
			"Faced",
      "Huge",
      "Gloomy",
      "Ill",
      "Illegal",
      "Hairy",
      "Fat",
      "Fake",
      "Meager",
      "Meek",
      "Excited",
      "Dizzy",
      "Dry",
      "Cultivated",
      "Curly",
      "Curvy",
      "Burly",
      "Buttery",
      "Comely",
      "Wise",
      "Tall",
      "Short",
			"Long",
      "Heavy",
      "Open",
			"Closed",
			"Fragile",
      "Fickle",
			"Mute",
			"Loud",
			"Busy",
      "Quant",
      "Regal",
      "Rich",
      "Roasting",
      "Spicy",
      "Salty",
      "Shoddy",
      "Shiny",
      "Thick",
      "Thin",
      "Thorny",
      "Unfit",
      "Vivid",
      "Worthy",
      "Wry",
      "Yearning",
      "Zesty",
      "Windy",
      "Warped",
      "Cold",
      "Warm",
      "Lukewarm",
      "Vacant",
      "Vapid",
      "Scaly",
      "Slushy",
      "Snowy",
      "Nifty",
      "Negative",
      "Unique",
      "Fluffy",
      "Moist",
      "Keen",
      "Jaded",
      "Livid",
      "Mediocre",
      "Clever",
      "Annoying",
      "Bad",
      "Brainy",
      "Curious",
      "Crazy",
      "Gifted",
      "Helpless",
      "Odd",
      "Poor",
      "Powerful",
      "Prickly",
      "Real",
      "Tame",
      "Talentless",
			"Bold",
      "Tough",
      "Vast",
      "Wild",
      "Dull",
      "Evil",
      "Defiant",
      "Itchy",
		  "Overcompensating",
      "Glitchy",
      "Tense",
      "Elated",
      "Friendly",
      "Young",
      "Rotten",
      "Ripe",
      "Bitter",
      "Fuzzy",
      "Greasy",
      "Grubby",
      "Creepy",
      "Damp",
      "Filthy",
      "Breezy",
      "Heavy",
      "Empty",
      "Adorable",
      "Bright"
    ]
  });
})();


